package edu.appstate.cs.quintus;

/**
 * Used to store data on each airport's code, country and location.
 * 
 * @author Dattasai Sagili
 * @version 12/06/2023
 */
public enum AirportCode 
{
    Aalborg("AAL", "Denmark", "Aalborg"), 
    Aalesund("AES", "Norway", "Aalesund"), 
    Aarhus("AAR", "Denmark", "Aarhus"), 
    Abbotsford_BC("YXX", "Canada", "Abbotsford, BC"),
    Aberdeen("ABZ", "Scotland", "Aberdeen"), 
    Aberdeen_SD("ABR", "USA", "Aberdeen, SD"), 
    Abidjan("ABJ", "Ivory Coast", "Abidjan"), 
    Abilene_TX("ABI", "USA", "Abilene, TX"), 
    Abu_Dhabi("AUH", "United Arab Emirates", "Abu Dhabi"), 
    Abuja("ABV", "Nigeria", "Abuja"), 
    Acapulco("ACA", "Mexico", "Acapulco"), 
    Accra("ACC", "Ghana", "Accra"), 
    Adana("ADA", "Turkey", "Adana"), 
    Addis_Ababa("ADD", "Ethiopia", "Addis Ababa"), 
    Adelaide_SA("ADL", "Australia", "Adelaide, SA"), 
    Aden("ADE", "Yemen", "Aden"), 
    Adiyaman("ADF", "Turkey", "Adiyaman"), 
    Agadir("AGA", "Morocco", "Agadir"), 
    Agana("GUM", "Guam", "Agana"), 
    Aguadilla("BQN", "Puerto Rico", "Aguadilla"), 
    Aguascalientes("AGU", "Mexico", "Aguascalientes"), 
    Ahe("AHE", "French Polynesia", "Ahe"), 
    Ahmedabad("AMD", "India", "Ahmedabad"), 
    Ajaccio_Corsica("AJA", "France", "Ajaccio, Corsica"), 
    Akita("AXT", "Japan", "Akita"), 
    Akron_OH("CAK", "USA", "Akron, OH"), 
    Alamosa_CO("ALS", "USA", "Alamosa, CO"), 
    Albany_GA("ABY", "USA", "Albany, GA"), 
    Albany_NY("ALB", "USA", "Albany, NY"), 
    Albenga("ALL", "Italy", "Albenga"), 
    Albuquerque_NM("ABQ", "USA", "Albuquerque, NM"), 
    Albury_NSW("ABX", "Australia", "Albury, NSW"),
    Alexandria("HBE", "Egypt", "Alexandria"), 
    Alexandria_LA("AEX", "USA", "Alexandria, LA"), 
    Alexandroupolis("AXD", "Greece", "Alexandroupolis"), 
    Alghero_Sardinia("AHO", "Italy", "Alghero, Sardinia"), 
    Algiers("ALG", "Algeria", "Algiers"), 
    Alicante("ALC", "Spain", "Alicante"), 
    Alice_Springs_NT("ASP", "Australia", "Alice Springs, NT"), 
    Alice_Town_North_Bimini_Island("NSB", "Bahamas", "Alice Town, North Bimini Island"), 
    Allentown_PA("ABE", "USA", "Allentown, PA"), 
    Alliance_NE("AIA", "USA", "Alliance, NE"), 
    Almaty("ALA", "Kazakhstan", "Almaty"), 
    Almeria("LEI", "Spain", "Almeria"), 
    Alor_Setar("AOR", "Malaysia", "Alor Setar"), 
    Alpena_MI("APN", "USA", "Alpena, MI"), 
    Alta("ALF", "Norway", "Alta"), 
    Altenrhein("ACH", "Switzerland", "Altenrhein"), 
    Altoona_PA("AOO", "USA", "Altoona, PA"), 
    Amarillo_TX("AMA", "USA", "Amarillo, TX"), 
    Amman("AMM", "Jordan", "Amman"), 
    Amsterdam("AMS", "Netherlands", "Amsterdam"), 
    Anahim_Lake_BC("YAA", "Canada", "Anahim Lake, BC"),
    Anchorage_AK("ANC", "USA", "Anchorage, AK"), 
    Ancona("AOI", "Italy", "Ancona"), 
    Andros_Town("ASD", "Bahamas", "Andros Town"), 
    Angeles_City("CRK", "Philippines", "Angeles City"), 
    Angra_do_Heroismo_Terceira_Island("TER", "Azores", "Angra do Heroismo, Terceira Island"), 
    Ankara("ESB", "Turkey", "Ankara"), 
    Annaba("AAE", "Algeria", "Annaba"), 
    Annecy("NCY", "France", "Annecy"), 
    Antalya("AYT", "Turkey", "Antalya"), 
    Antananarivo("TNR", "Madagascar", "Antananarivo"), 
    Antofagasta("ANF", "Chile", "Antofagasta"), 
    Antwerp("ANR", "Belgium", "Antwerp"), 
    Aomori("AOJ", "Japan", "Aomori"), 
    Aosta("AOT", "Italy", "Aosta"), 
    Appleton_WI("ATW", "USA", "Appleton, WI"), 
    Ardabil("ADU", "Iran", "Ardabil"), 
    Arequipa("AQP", "Peru", "Arequipa"), 
    Argostoli_Kefalonia_Island("EFL", "Greece", "Argostoli, Kefalonia Island"), 
    Arica("ARI", "Chile", "Arica"), 
    Arkhangelsk("ARH", "Russia", "Arkhangelsk"), 
    Armidale_NSW("ARM", "Australia", "Armidale, NSW"), 
    Arrecife_Lanzarote_Island("ACE", "Canary Islands", "Arrecife, Lanzarote Island"), 
    Arusha("ARK", "Tanzania", "Arusha"), 
    Arviat_NT("YEK", "Canada", "Arviat, NT"),
    Arvidsjaur("AJR", "Sweden", "Arvidsjaur"), 
    Asheville_NC("AVL", "USA", "Asheville, NC"), 
    Asmara("ASM", "Eritrea", "Asmara"), 
    Aspen_CO("ASE", "USA", "Aspen, CO"), 
    Astana("TSE", "Kazakhstan", "Astana"), 
    Asuncion("ASU", "Paraguay", "Asuncion"), 
    Aswan("ASW", "Egypt", "Aswan"), 
    Athens("ATH", "Greece", "Athens"), 
    Athens_GA("AHN", "USA", "Athens, GA"), 
    Atlanta_GA("ATL", "USA", "Atlanta, GA"), 
    Atlantic_City_NJ("ACY", "USA", "Atlantic City, NJ"), 
    Auckland("AKL", "New Zealand", "Auckland"), 
    Augusta_GA("AGS", "USA", "Augusta, GA"), 
    Augusta_ME("AUG", "USA", "Augusta, ME"), 
    Austin_TX("AUS", "USA", "Austin, TX"), 
    Avarua_Rarotonga_Island("RAR", "Cook Islands", "Avarua, Rarotonga Island"), 
    Ayers_Rock_NT("AYQ", "Australia", "Ayers Rock, NT"), 
    Bacolod("BCD", "Philippines", "Bacolod"), 
    Badajoz("BJZ", "Spain", "Badajoz"), 
    Baghdad("SDA", "Iraq", "Baghdad"), 
    Bagotville_QC("YBG", "Canada", "Bagotville, QC"),
    Baie_Comeau_QC("YBC", "Canada", "Baie-Comeau, QC"), 
    Bakersfield_CA("BFL", "USA", "Bakersfield, CA"),
    Baku("GYD", "Azerbaijan", "Baku"), 
    Balaton("SOB", "Hungary", "Balaton"), 
    Balephuil("TRE", "Scotland", "Balephuil"), 
    Balikpapan_Kalimantan("BPN", "Indonesia", "Balikpapan, Kalimantan"), 
    Ballina_NSW("BNK", "Australia", "Ballina, NSW"), 
    Balmaceda("BBA", "Chile", "Balmaceda"), 
    Baltimore_MD("BWI", "USA", "Baltimore, MD"), 
    Ban_Me_Thuot("BMV", "Vietnam", "Ban Me Thuot"), 
    Bandar_Seri_Begawan("BWN", "Brunei", "Bandar Seri Begawan"), 
    Bangalore("BLR", "India", "Bangalore"), 
    Bangda("BPX", "China", "Bangda"), 
    Bangkok("BKK", "Thailand", "Bangkok"), 
    Bangor_ME("BGR", "USA", "Bangor, ME"), 
    Bangui("BGF", "Central African Republic", "Bangui"), 
    Banjul("BJL", "Gambia", "Banjul"), 
    Bar_Harbor_ME("BHB", "USA", "Bar Harbor, ME"), 
    Barcelona("BCN", "Spain", "Barcelona"), 
    Bardufoss("BDU", "Norway", "Bardufoss"), 
    Bari("BRI", "Italy", "Bari"), 
    Barisal("BZL", "Bangladesh", "Barisal"), 
    Barranquilla("BAQ", "Colombia", "Barranquilla"), 
    Barrow_AK("BRW", "USA", "Barrow, AK"), 
    Basel("BSL", "Switzerland", "Basel"), 
    Basseterre("SKB", "St. Kitts", "Basseterre"), 
    Bastia_Corsica("BIA", "France", "Bastia, Corsica"), 
    Bathurst_NSW("BHS", "Australia", "Bathurst, NSW"), 
    Baton_Rouge_LA("BTR", "USA", "Baton Rouge, LA"), 
    Bauru("BAU", "Brazil", "Bauru"), 
    Beaumont_TX("BPT", "USA", "Beaumont, TX"), 
    Beauvais("BVA", "France", "Beauvais"), 
    Beckley_WV("BKW", "USA", "Beckley, WV"), 
    Bedford_MA("BED", "USA", "Bedford, MA"), 
    Beef_Island_Tortola("EIS", "British Virgin Islands", "Beef Island, Tortola"), 
    Beijing("BJS", "China", "Beijing"), 
    Beirut("BEY", "Lebanon", "Beirut"), 
    Belem("BEL", "Brazil", "Belem"),
    Belfast("BHD", "Northern Ireland", "Belfast"), 
    Belgrade("BEG", "Serbia and Montenegro", "Belgrade"), 
    Belize_City("BZE", "Belize", "Belize City"), 
    Bellingham_WA("BLI", "USA", "Bellingham, WA"), 
    Belo_Horizonte("CNF", "Brazil", "Belo Horizonte"), 
    Bemidji_MN("BJI", "USA", "Bemidji, MN"), 
    Benbecula("BEB", "Scotland", "Benbecula"), 
    Benguela("BUG", "Angola", "Benguela"), 
    Bergen("BGO", "Norway", "Bergen"), 
    Berlin("BER", "Germany", "Berlin"),
    Bethel_AK("BET", "USA", "Bethel, AK"), 
    Bettles_AK("BTT", "USA", "Bettles, AK"), 
    Biak_Papua("BIK", "Indonesia", "Biak, Papua"), 
    Biarritz("BIQ", "France", "Biarritz"), 
    Bilbao("BIO", "Spain", "Bilbao"), 
    Billings_MT("BIL", "USA", "Billings, MT"), 
    Billund("BLL", "Denmark", "Billund"), 
    Binghamton_NY("BGM", "USA", "Binghamton, NY"), 
    Bintulu_Sarawak("BTU", "Malaysia", "Bintulu, Sarawak"), 
    Birmingham("BHX", "England", "Birmingham"), 
    Birmingham_AL("BHM", "USA", "Birmingham, AL"), 
    Bishkek("FRU", "Kyrgyzstan", "Bishkek"), 
    Bismarck_ND("BIS", "USA", "Bismarck, ND"), 
    Bissau("OXB", "Guinea-Bissau", "Bissau"), 
    Blantyre("BLZ", "Malawi", "Blantyre"), 
    Blenheim("BHE", "New Zealand", "Blenheim"), 
    Bloemfontein("BFN", "South Africa", "Bloemfontein"), 
    Bloomington_IL("BMI", "USA", "Bloomington, IL"), 
    Bloomington_IN("BMG", "USA", "Bloomington, IN"), 
    Bluefield_WV("BLF", "USA", "Bluefield, WV"), 
    Bodo("BOO", "Norway", "Bodo"), 
    Bogota("BOG", "Colombia", "Bogota"), 
    Boise_ID("BOI", "USA", "Boise, ID"), 
    Bologna("BLQ", "Italy", "Bologna"), 
    Bolzano("BZO", "Italy", "Bolzano"), 
    Bordeaux("BOD", "France", "Bordeaux"), 
    Borlange("BLE", "Sweden", "Borlange"), 
    Boston_MA("BOS", "USA", "Boston, MA"), 
    Bozeman_MT("BZN", "USA", "Bozeman, MT"), 
    Brasilia("BSB", "Brazil", "Brasilia"), 
    Bratislava("BTS", "Slovakia", "Bratislava"), 
    Brazzaville("BZV", "Congo", "Brazzaville"), 
    Bremen("BRE", "Germany", "Bremen"), 
    Brest("BES", "France", "Brest"), 
    Bridgetown("BGI", "Barbados", "Bridgetown"), 
    Brindisi("BDS", "Italy", "Brindisi"), 
    Brisbane_QLD("BNE", "Australia", "Brisbane, Qld"), 
    Bristol("BRS", "England", "Bristol"), 
    Broken_Hill_NSW("BHQ", "Australia", "Broken Hill, NSW"), 
    Brookings_SD("BKX", "USA", "Brookings, SD"), 
    Broome_WA("BME", "Australia", "Broome, WA"), 
    Brownsville_TX("BRO", "USA", "Brownsville, TX"), 
    Brunswick_GA("BQK", "USA", "Brunswick, GA"), 
    Brussels("BRU", "Belgium", "Brussels"), 
    Bucharest("OTP", "Romania", "Bucharest"), 
    Budapest("BUD", "Hungary", "Budapest"), 
    Buenos_Aires("EZE", "Argentina", "Buenos Aires"), 
    Buffalo_NY("BUF", "USA", "Buffalo, NY"), 
    Bujumbura("BJM", "Burundi", "Bujumbura"), 
    Bulawayo("BUQ", "Zimbabwe", "Bulawayo"), 
    Bundaberg_QLD("BDB", "Australia", "Bundaberg, Qld"), 
    Burbank_CA("BUR", "USA", "Burbank, CA"), 
    Buri_Ram("BFV", "Thailand", "Buri Ram"), 
    Burlington_IA("BRL", "USA", "Burlington, IA"), 
    Burlington_MA("BBF", "USA", "Burlington, MA"), 
    Burlington_VT("BTV", "USA", "Burlington, VT"), 
    Busan_Korea("PUS", "Republic of", "Busan, Korea"), 
    Butte_MT("BTM", "USA", "Butte, MT"), 
    Butuan("BXU", "Philippines", "Butuan"), 
    Bydgoszcz("BZG", "Poland", "Bydgoszcz"), 
    Caen("CFR", "France", "Caen"), 
    Cagayan_de_Oro("CGY", "Philippines", "Cagayan de Oro"), 
    Cagliari_Sardinia("CAG", "Italy", "Cagliari, Sardinia"), 
    Cairns_QLD("CNS", "Australia", "Cairns, Qld"), 
    Cairo("CAI", "Egypt", "Cairo"), 
    Calcutta("CCU", "India", "Calcutta"), 
    Calgary_AB("YYC", "Canada", "Calgary, AB"),
    Cali("CLO", "Colombia", "Cali"), 
    Calvi_Corsica("CLY", "France", "Calvi, Corsica"), 
    Campbell_River_BC("YBL", "Canada", "Campbell River, BC"),
    Campbeltown("CAL", "Scotland", "Campbeltown"), 
    Campeche("CPE", "Mexico", "Campeche"), 
    Canberra_ACT("CBR", "Australia", "Canberra, A.C.T."), 
    Cancun("CUN", "Mexico", "Cancun"),
    Cap_aux_Meules_Magdalens_Islands_QC("YGR", "Canada", "Cap-aux-Meules, Magdalens Islands, QC"), 
    Cape_Girardeau_MO("CGI", "USA", "Cape Girardeau, MO"), 
    Cape_Town("CPT", "South Africa", "Cape Town"), 
    Caracas("CCS", "Venezuela", "Caracas"), 
    Cardiff("CWL", "Wales", "Cardiff"), 
    Carlsbad_CA("CLD", "USA", "Carlsbad, CA"), 
    Carlsbad_NM("CNM", "USA", "Carlsbad, NM"), 
    Cartagena("CTG", "Colombia", "Cartagena"), 
    Casablanca("CMN", "Morocco", "Casablanca"), 
    Casper_WY("CPR", "USA", "Casper, WY"), 
    Castlegar_BC("YCG", "Canada", "Castlegar, BC"),
    Castries("SLU", "St. Lucia", "Castries"), 
    Catania_Sicily("CTA", "Italy", "Catania, Sicily"), 
    Cayenne("CAY", "French Guiana", "Cayenne"), 
    Cayman_Brac("CYB", "Cayman Islands", "Cayman Brac"), 
    Cebu("CEB", "Philippines", "Cebu"), 
    Cedar_Rapids_IA("CID", "USA", "Cedar Rapids, IA"), 
    Ceduna_SA("CED", "Australia", "Ceduna, SA"), 
    Champaign_IL("CMI", "USA", "Champaign, IL"), 
    Changchun("CGQ", "China", "Changchun"), 
    Changsha("CSX", "China", "Changsha"), 
    Chania_Crete("CHQ", "Greece", "Chania, Crete"), 
    Charleston_SC("CHS", "USA", "Charleston, SC"), 
    Charleston_WV("CRW", "USA", "Charleston, WV"), 
    Charleville_QLD("CTL", "Australia", "Charleville, Qld"), 
    Charlotte_Amalie_St_Thomas("STT", "U.S. Virgin Islands", "Charlotte Amalie, St. Thomas"), 
    Charlotte_NC("CLT", "USA", "Charlotte, NC"), 
    Charlottesville_VA("CHO", "USA", "Charlottesville, VA"), 
    Charlottetown_PE("YYG", "Canada", "Charlottetown, PE"),
    Chattanooga_TN("CHA", "USA", "Chattanooga, TN"), 
    Chengdu("CTU", "China", "Chengdu"), 
    Chennai("MAA", "India", "Chennai (Madras)"), 
    Chetumal("CTM", "Mexico", "Chetumal"), 
    Cheyenne_WY("CYS", "USA", "Cheyenne, WY"), 
    Chiang_Mai("CNX", "Thailand", "Chiang Mai"), 
    Chiang_Rai("CEI", "Thailand", "Chiang Rai"), 
    Chibougamau_QC("YMT", "Canada", "Chibougamau, QC"),
    Chicago_IL1("CHI", "USA", "Chicago, IL"), 
    Chicago_IL2("MDW", "USA", "Chicago, IL (Midway)"), 
    Chicago_IL3("ORD", "USA", "Chicago, IL (O'Hare Intl)"), 
    Chico_CA("CIC", "USA", "Chico, CA"), 
    Chihuahua("CUU", "Mexico", "Chihuahua"), 
    Chios("JKH", "Greece", "Chios"), 
    Chisinau("KIV", "Moldova", "Chisinau"), 
    Chongqing("CKG", "China", "Chongqing"), 
    Christchurch("CHC", "New Zealand", "Christchurch"), 
    Christiansted_St_Croix("STX", "U.S. Virgin Islands", "Christiansted, St. Croix"), 
    Churchill_MB("YYQ", "Canada", "Churchill, MB"),
    Cincinnati_OH("CVG", "USA", "Cincinnati, OH"), 
    Ciudad_Bolivar("CBL", "Venezuela", "Ciudad Bolivar"), 
    Ciudad_Del_Carmen("CME", "Mexico", "Ciudad Del Carmen"), 
    Ciudad_del_Este("AGT", "Paraguay", "Ciudad del Este"), 
    Ciudad_Juarez("CJS", "Mexico", "Ciudad Juarez"), 
    Ciudad_Obregon("CEN", "Mexico", "Ciudad Obregon"), 
    Ciudad_Victoria("CVM", "Mexico", "Ciudad Victoria"), 
    Clarksburg_WV("CKB", "USA", "Clarksburg, WV"), 
    Clermont_Ferrand("CFE", "France", "Clermont-Ferrand"), 
    Cleveland_OH("CLE", "USA", "Cleveland, OH"), 
    Clovis_NM("CVN", "USA", "Clovis, NM"), 
    Cockburn_Town_San_Salvador_Island("ZSA", "Bahamas", "Cockburn Town, San Salvador Island"), 
    Cody_WY("COD", "USA", "Cody, WY"), 
    Coffs_Harbour_NSW("CFS", "Australia", "Coffs Harbour, NSW"), 
    Colima("CLQ", "Mexico", "Colima"), 
    College_Station_TX("CLL", "USA", "College Station, TX"), 
    Cologne("CGN", "Germany", "Cologne"), 
    Colombo("CMB", "Sri Lanka", "Colombo"), 
    Colorado_Springs_CO("COS", "USA", "Colorado Springs, CO"), 
    Columbia_MO("COU", "USA", "Columbia, MO"), 
    Columbia_SC("CAE", "USA", "Columbia, SC"), 
    Columbus_GA("CSG", "USA", "Columbus, GA"), 
    Columbus_IN("CLU", "USA", "Columbus, IN"), 
    Columbus_MS("GTR", "USA", "Columbus, MS"), 
    Columbus_NE("OLU", "USA", "Columbus, NE"), 
    Columbus_OH("CMH", "USA", "Columbus, OH"), 
    Conakry("CKY", "Guinea", "Conakry"), 
    Concepcion("CCP", "Chile", "Concepcion"), 
    Connaught("NOC", "Ireland", "Connaught"), 
    Coober_Pedy_SA("CPD", "Australia", "Coober Pedy, SA"), 
    Copenhagen("CPH", "Denmark", "Copenhagen"), 
    Copiapo("CPO", "Chile", "Copiapo"), 
    Cordoba("COR", "Argentina", "Cordoba"), 
    Cordova_AK("CDV", "USA", "Cordova, AK"), 
    Cork("ORK", "Ireland", "Cork"), 
    Corpus_Christi_TX("CRP", "USA", "Corpus Christi, TX"), 
    Cotabato("CBO", "Philippines", "Cotabato"), 
    Cozumel("CZM", "Mexico", "Cozumel"), 
    Cranbrook_BC("YXC", "Canada", "Cranbrook, BC"),
    Crotone("CRV", "Italy", "Crotone"), 
    Cubi_Point_Nas("NCP", "Philippines", "Cubi Point Nas"), 
    Culiacan("CUL", "Mexico", "Culiacan"), 
    Curitiba("CWB", "Brazil", "Curitiba"), 
    Cusco("CUZ", "Peru", "Cusco"), 
    Da_Nang("DAD", "Vietnam", "Da Nang"), 
    Dakar("DKR", "Senegal", "Dakar"), 
    Dalaman("DLM", "Turkey", "Dalaman"), 
    Dali_City("DLU", "China", "Dali City"), 
    Dalian("DLC", "China", "Dalian"), 
    Dallas_TX1("DFW", "USA", "Dallas, TX (Dallas/Fort Worth)"),
    Dallas_TX2("DAL", "USA", "Dallas, TX (Lovefield)"),  
    Damascus("DAM", "Syria", "Damascus"), 
    Dangriga("DGA", "Belize", "Dangriga"), 
    Dar_es_Salaam("DAR", "Tanzania", "Dar es Salaam"), 
    Darwin_NT("DRW", "Australia", "Darwin, NT"), 
    Davao("DVO", "Philippines", "Davao"), 
    Dawadmi("DWD", "Saudi Arabia", "Dawadmi"), 
    Dayong("DYG", "China", "Dayong"), 
    Dayton_OH("DAY", "USA", "Dayton, OH"), 
    Daytona_Beach_FL("DAB", "USA", "Daytona Beach, FL"), 
    Deadmans_Cay_Long_Island("LGI", "Bahamas", "Deadmans Cay, Long Island"), 
    Deboyne("DOY", "Papua-New Guinea", "Deboyne"), 
    Decatur_IL("DEC", "USA", "Decatur, IL"), 
    Deer_Lake_NL("YDF", "Canada", "Deer Lake, NL"),
    Delhi("DEL", "India", "Delhi"), 
    Denpasar_Bali("DPS", "Indonesia", "Denpasar, Bali"), 
    Denver_CO("DEN", "USA", "Denver, CO"), 
    Des_Moines_IA("DSM", "USA", "Des Moines, IA"),
    Detroit_MI("DTW", "USA", "Detroit, MI"), 
    Devils_Lake_ND("DVL", "USA", "Devils Lake, ND"), 
    Devonport_Tas("DPO", "Australia", "Devonport, Tas"), 
    Dhahran("DHA", "Saudi Arabia", "Dhahran"), 
    Dhaka("DAC", "Bangladesh", "Dhaka"), 
    Dickinson_ND("DIK", "USA", "Dickinson, ND"), 
    Dien_Bien_Phu("DIN", "Vietnam", "Dien-Bien-Phu"), 
    Dillingham_AK("DLG", "USA", "Dillingham, AK"), 
    Dipolog("DPL", "Philippines", "Dipolog"), 
    Djibouti("JIB", "Djibouti", "Djibouti"), 
    Dnepropetrovsk("DNK", "Ukraine", "Dnepropetrovsk"), 
    Dodge_City_KS("DDC", "USA", "Dodge City, KS"), 
    Doha("DOH", "Qatar", "Doha"), 
    Doncaster("DSA", "England", "Doncaster"), 
    Donetsk("DOK", "Ukraine", "Donetsk"), 
    Dortmund("DTM", "Germany", "Dortmund"), 
    Dothan_AL("DHN", "USA", "Dothan, AL"), 
    Douala("DLA", "Cameroon", "Douala"), 
    Dresden("DRS", "Germany", "Dresden"), 
    Dryden_ON("YHD", "Canada", "Dryden, ON"),
    Du_Bois_PA("DUJ", "USA", "Du Bois, PA"), 
    Dubai("DXB", "United Arab Emirates", "Dubai"), 
    Dubbo_NSW("DBO", "Australia", "Dubbo, NSW"), 
    Dublin("DUB", "Ireland", "Dublin"), 
    Dubrovnik("DBV", "Croatia", "Dubrovnik"), 
    Dubuque_IA("DBQ", "USA", "Dubuque, IA"), 
    Duluth_MN("DLH", "USA", "Duluth, MN"), 
    Dumaguete("DGT", "Philippines", "Dumaguete"), 
    Dunedin("DUD", "New Zealand", "Dunedin"), 
    Durango("DGO", "Mexico", "Durango"), 
    Durango_CO("DRO", "USA", "Durango, CO"), 
    Durban("DUR", "South Africa", "Durban"), 
    Dushanbe("DYU", "Tajikistan", "Dushanbe"), 
    Dusseldorf("DUS", "Germany", "Dusseldorf"), 
    Dutch_Harbor_Un_Island_AK("DUT", "USA", "Dutch Harbor, Un Island, AK"), 
    East_London("ELS", "South Africa", "East London"), 
    East_Midlands("EMA", "England", "East Midlands"), 
    Eau_Claire_WI("EAU", "USA", "Eau Claire, WI"), 
    Edinburgh("EDI", "Scotland", "Edinburgh"), 
    Edmonton_AB("YEG", "Canada", "Edmonton, AB"),
    Eek_AK("EEK", "USA", "Eek, AK"), 
    Ekaterinburg_Siberia("SVX", "Russia", "Ekaterinburg, Siberia"), 
    El_Calafate("FTE", "Argentina", "El Calafate"), 
    El_Centro_CA("IPL", "USA", "El Centro, CA"), 
    El_Dorado_AR("ELD", "USA", "El Dorado, AR"), 
    El_Paso_TX("ELP", "USA", "El Paso, TX"), 
    El_Salvador("ESR", "Chile", "El Salvador"), 
    Elko_NV("EKO", "USA", "Elko, NV"), 
    Elmira_NY("ELM", "USA", "Elmira, NY"), 
    Emerald_QLD("EMD", "Australia", "Emerald, Qld"), 
    Enid_OK("WDG", "USA", "Enid, OK"), 
    Entebbe("EBB", "Uganda", "Entebbe"), 
    Erfurt("ERF", "Germany", "Erfurt"), 
    Erie_PA("ERI", "USA", "Erie, PA"), 
    Esbjerg("EBJ", "Denmark", "Esbjerg"), 
    Escanaba_MI("ESC", "USA", "Escanaba, MI"), 
    Eugene_OR("EUG", "USA", "Eugene, OR"), 
    Eureka_CA("ACV", "USA", "Eureka, CA"), 
    Evansville_IN("EVV", "USA", "Evansville, IN"), 
    Evenes("EVE", "Norway", "Evenes"), 
    Fairbanks_AK("FAI", "USA", "Fairbanks, AK"), 
    Fargo_ND("FAR", "USA", "Fargo, ND"), 
    Farmington_NM("FMN", "USA", "Farmington, NM"), 
    Faro("FAO", "Portugal", "Faro"), 
    Fayetteville_AR("XNA", "USA", "Fayetteville, AR"), 
    Fayetteville_NC("FAY", "USA", "Fayetteville, NC"), 
    Fernando_de_Noronha("FEN", "Brazil", "Fernando de Noronha"), 
    Figari_Corsica("FSC", "France", "Figari, Corsica"), 
    Flagstaff_AZ("FLG", "USA", "Flagstaff, AZ"), 
    Flin_Flon_MB("YFO", "Canada", "Flin Flon, MB"),
    Flint_MI("FNT", "USA", "Flint, MI"), 
    Florence("FLR", "Italy", "Florence"), 
    Florence_SC("FLO", "USA", "Florence, SC"), 
    Flores("FRS", "Guatemala", "Flores"), 
    Fort_Dodge_IA("FOD", "USA", "Fort Dodge, IA"), 
    Fort_Lauderdale_FL("FLL", "USA", "Fort Lauderdale, FL"), 
    Fort_Leonard_Wood_MO("TBN", "USA", "Fort Leonard Wood, MO"), 
    Fort_McMurray_AB("YMM", "Canada", "Fort McMurray, AB"),
    Fort_Myers_FL("RSW", "USA", "Fort Myers, FL"), 
    Fort_Nelson_BC("YYE", "Canada", "Fort Nelson, BC"),
    Fort_Saint_John_BC("YXJ", "Canada", "Fort Saint John, BC"),
    Fort_Smith_AR("FSM", "USA", "Fort Smith, AR"), 
    Fort_Smith_NT("YSM", "Canada", "Fort Smith, NT"), 
    Fort_Walton_Beach_FL("VPS", "USA", "Fort Walton Beach, FL"), 
    Fort_Wayne_IN("FWA", "USA", "Fort Wayne, IN"), 
    Fort_Yukon_AK("FYU", "USA", "Fort Yukon, AK"), 
    Fort_de_France("FDF", "Martinique", "Fort-de-France"), 
    Frankfurt("FRA", "Germany", "Frankfurt"), 
    Fredericton_NB("YFC", "Canada", "Fredericton, NB"),
    Freeport_Grand_Bahama_Island("FPO", "Bahamas", "Freeport, Grand Bahama Island"), 
    Freetown("FNA", "Sierra Leone", "Freetown"), 
    Fresno_CA("FAT", "USA", "Fresno, CA"), 
    Friedrichshafen("FDH", "Germany", "Friedrichshafen"), 
    Fukuoka("FUK", "Japan", "Fukuoka"), 
    Fukushima("FKS", "Japan", "Fukushima"), 
    Funchal("FNC", "Madeira", "Funchal"), 
    Fuzhou("FOC", "China", "Fuzhou"), 
    Gainesville_FL("GNV", "USA", "Gainesville, FL"), 
    Gander_NL("YQX", "Canada", "Gander, NL"),
    Garden_City_KS("GCK", "USA", "Garden City, KS"), 
    Gaspe_QC("YGP", "Canada", "Gaspe, QC"),
    Gdansk("GDN", "Poland", "Gdansk"), 
    General_Santos("GES", "Philippines", "General Santos"), 
    Geneva("GVA", "Switzerland", "Geneva"), 
    Genoa("GOA", "Italy", "Genoa"), 
    George_Town_Great_Exuma_Island("GGT", "Bahamas", "George Town, Great Exuma Island"), 
    Georgetown("GEO", "Guyana", "Georgetown"), 
    Georgetown_Grand_Cayman_Island("GCM", "Cayman Islands", "Georgetown, Grand Cayman Island"), 
    Gillette_WY("GCC", "USA", "Gillette, WY"), 
    Gisborne("GIS", "New Zealand", "Gisborne"), 
    Gladstone_QLD("GLT", "Australia", "Gladstone, Qld"), 
    Glasgow("GLA", "Scotland", "Glasgow"),
    Glendive_MT("GDV", "USA", "Glendive, MT"), 
    Gold_Coast_QLD("OOL", "Australia", "Gold Coast, Qld"), 
    Gothenburg("GOT", "Sweden", "Gothenburg"), 
    Gove_NT("GOV", "Australia", "Gove, NT"), 
    Governors_Harbour_Eleuthera_Island("GHB", "Bahamas", "Governor's Harbour, Eleuthera Island"), 
    Granada("GRX", "Spain", "Granada"), 
    Grand_Forks_ND("GFK", "USA", "Grand Forks, ND"), 
    Grand_Island_NE("GRI", "USA", "Grand Island, NE"), 
    Grand_Junction_CO("GJT", "USA", "Grand Junction, CO"), 
    Grand_Rapids_MI("GRR", "USA", "Grand Rapids, MI"), 
    Grande_Prairie_AB("YQU", "Canada", "Grande Prairie, AB"),
    Graz("GRZ", "Austria", "Graz"), 
    Great_Bend_KS("GBD", "USA", "Great Bend, KS"), 
    Great_Falls_MT("GTF", "USA", "Great Falls, MT"), 
    Green_Bay_WI("GRB", "USA", "Green Bay, WI"), 
    Greenbrier_WV("LWB", "USA", "Greenbrier, WV"), 
    Greensboro_NC("GSO", "USA", "Greensboro, NC"), 
    Greenville_MS("GLH", "USA", "Greenville, MS"), 
    Greenville_NC("PGV", "USA", "Greenville, NC"), 
    Greenville_SC("GSP", "USA", "Greenville, SC"), 
    Griffith_NSW("GFF", "Australia", "Griffith, NSW"), 
    Guadalajara("GDL", "Mexico", "Guadalajara"), 
    Guangzhou("CAN", "China", "Guangzhou"), 
    Guatemala_City("GUA", "Guatemala", "Guatemala City"), 
    Guayaquil("GYE", "Ecuador", "Guayaquil"), 
    Guaymas("GYM", "Mexico", "Guaymas"), 
    Guernsey("GCI", "Channel Islands", "Guernsey"), 
    Guilin("KWL", "China", "Guilin"), 
    Gulfport_MS("GPT", "USA", "Gulfport, MS"), 
    Gunnison_CO("GUC", "USA", "Gunnison, CO"), 
    Gustavia("SBH", "St. Barts", "Gustavia"), 
    Hagerstown_MD("HGR", "USA", "Hagerstown, MD"), 
    Haikou_Hainan_Island("HAK", "China", "Haikou, Hainan Island"), 
    Hailar("HLD", "China", "Hailar"), 
    Hakodate("HKD", "Japan", "Hakodate"), 
    Halifax_NS("YHZ", "Canada", "Halifax, NS"),
    Halmstad("HAD", "Sweden", "Halmstad"), 
    Hamburg("HAM", "Germany", "Hamburg"), 
    Hamilton1("BDA", "Bermuda", "Hamilton"), 
    Hamilton2("HLZ", "New Zealand", "Hamilton"), 
    Hamilton_Island_Whitsunday_Island_QLD("HTI", "Australia", "Hamilton Island, Whitsunday Island, Qld"), 
    Hamilton_ON("YHM", "Canada", "Hamilton, ON"), 
    Hammerfest("HFT", "Norway", "Hammerfest"), 
    Hana_Maui_HI("HNM", "USA", "Hana, Maui, HI"), 
    Hancock_MI("CMX", "USA", "Hancock, MI"), 
    Hanga_Roa_Easter_Island("IPC", "Chile", "Hanga Roa, Easter Island"), 
    Hangzhou("HGH", "China", "Hangzhou"), 
    Hannover("HAJ", "Germany", "Hannover"), 
    Hanoi("HAN", "Vietnam", "Hanoi"), 
    Harare("HRE", "Zimbabwe", "Harare"), 
    Harbin("HRB", "China", "Harbin"), 
    Harlingen_TX("HRL", "USA", "Harlingen, TX"), 
    Harrisburg_PA("MDT", "USA", "Harrisburg, PA"), 
    Harrison_AR("HRO", "USA", "Harrison, AR"), 
    Hartford_CT("BDL", "USA", "Hartford, CT"), 
    Hat_Yai("HDY", "Thailand", "Hat Yai"), 
    Haugesund("HAU", "Norway", "Haugesund"), 
    Havana("HAV", "Cuba", "Havana"), 
    Havre_MT("HVR", "USA", "Havre, MT"), 
    Hays_KS("HYS", "USA", "Hays, KS"), 
    Hefei("HFE", "China", "Hefei"), 
    Helena_MT("HLN", "USA", "Helena, MT"), 
    Helsingborg("AGH", "Sweden", "Helsingborg"), 
    Helsinki("HEL", "Finland", "Helsinki"), 
    Hemavan("HMV", "Sweden", "Hemavan"), 
    Hengchun("HCN", "Taiwan", "Hengchun"), 
    Heraklion_Crete("HER", "Greece", "Heraklion, Crete"), 
    Hermosillo("HMO", "Mexico", "Hermosillo"), 
    Hibbing_MN("HIB", "USA", "Hibbing, MN"), 
    Hilo_Hawaii("Big", "USA", "Hilo, Hawaii"), 
    Hilton_Head_Island_SC("HHH", "USA", "Hilton Head Island, SC"), 
    Ho_Chi_Minh_City("SGN", "Vietnam", "Ho Chi Minh City (Saigon)"), 
    Hobart_Tas("HBA", "Australia", "Hobart, Tas"), 
    Hobbs_NM("HOB", "USA", "Hobbs, NM"), 
    Hof("HOQ", "Germany", "Hof"), 
    Hohhot("HET", "China", "Hohhot"), 
    Hokitika("HKK", "New Zealand", "Hokitika"), 
    Homer_AK("HOM", "USA", "Homer, AK"), 
    Hong_Kong("HKG", "China", "Hong Kong"), 
    Honiara_Guadalcanal("HIR", "Solomon Islands", "Honiara, Guadalcanal"), 
    Honolulu_Oahu_HI("HNL", "USA", "Honolulu, Oahu, HI"), 
    Hoolehua_Molokai_HI("MKK", "USA", "Hoolehua, Molokai, HI"), 
    Horn_Island_QLD("HID", "Australia", "Horn Island, Qld"), 
    Hot_Springs_AR("HOT", "USA", "Hot Springs, AR"), 
    Houmt_Souk("DJE", "Tunisia", "Houmt Souk"), 
    Houston_TX1("IAH", "USA", "Houston, TX (George Bush Intercontinental)"), 
    Houston_TX2("EFD", "USA", "Houston, TX (Ellington)"), 
    Houston_TX3("HOU", "USA", "Houston, TX (Willian P. Hobby)"), 
    Hualien("HUN", "Taiwan", "Hualien"), 
    Hue("HUI", "Vietnam", "Hue"), 
    Humberside("HUY", "England", "Humberside"), 
    Huntington_WV("HTS", "USA", "Huntington, WV"), 
    Huntsville_AL("HSV", "USA", "Huntsville, AL"), 
    Hurghada("HRG", "Egypt", "Hurghada"), 
    Huron_SD("HON", "USA", "Huron, SD"), 
    Hyannis_MA("HYA", "USA", "Hyannis, MA"), 
    Hyderabad("HYD", "India", "Hyderabad"), 
    Ibadan("IBA", "Nigeria", "Ibadan"), 
    Ibiza("IBZ", "Spain", "Ibiza"), 
    Idaho_Falls_ID("IDA", "USA", "Idaho Falls, ID"), 
    Ikaria_Island("JIK", "Greece", "Ikaria Island"), 
    Iloilo("ILO", "Philippines", "Iloilo"), 
    Indianapolis_IN("IND", "USA", "Indianapolis, IN"), 
    Innsbruck("INN", "Austria", "Innsbruck"), 
    International_Falls_MN("INL", "USA", "International Falls, MN"), 
    Invercargill("IVC", "New Zealand", "Invercargill"), 
    Inverness("INV", "Scotland", "Inverness"), 
    Inyokern_CA("IYK", "USA", "Inyokern, CA"), 
    Ioannina("IOA", "Greece", "Ioannina"), 
    Ipoh("IPH", "Malaysia", "Ipoh"), 
    Iqaluit_NU("YFB", "Canada", "Iqaluit, NU"),
    Irkutsk_Siberia("IKT", "Russia", "Irkutsk, Siberia"), 
    Iron_Mountain_MI("IMT", "USA", "Iron Mountain, MI"), 
    Ironwood_MI("IWD", "USA", "Ironwood, MI"), 
    Islamabad_Rawalpindi("ISB", "Pakistan", "Islamabad-Rawalpindi"), 
    Islay_Island("ILY", "Scotland", "Islay Island"), 
    Islip_NY("ISP", "USA", "Islip, NY"), 
    Istanbul1("IST", "Turkey", "Istanbul (New Istanbul)"), 
    Istanbul2("SAW", "Turkey", "Istanbul (Sabiha Gokcen)"), 
    Ithaca_NY("ITH", "USA", "Ithaca, NY"), 
    Ivalo("IVL", "Finland", "Ivalo"), 
    Iwami("IWJ", "Japan", "Iwami"), 
    Ixtapa("ZIH", "Mexico", "Ixtapa"), 
    Izmir("ADB", "Turkey", "Izmir"), 
    Izumo("IZO", "Japan", "Izumo"), 
    Jackson_Hole_WY("JAC", "USA", "Jackson Hole, WY"), 
    Jackson_MS("JAN", "USA", "Jackson, MS"), 
    Jackson_TN("MKL", "USA", "Jackson, TN"), 
    Jacksonville_FL("JAX", "USA", "Jacksonville, FL"), 
    Jacksonville_NC("OAJ", "USA", "Jacksonville, NC"), 
    Jakarta_Java("CGK", "Indonesia", "Jakarta, Java"),
    Jalapa("JAL", "Mexico", "Jalapa"), 
    Jamestown_ND("JMS", "USA", "Jamestown, ND"), 
    Jamestown_NY("JHW", "USA", "Jamestown, NY"), 
    Jeddah("JED", "Saudi Arabia", "Jeddah"), 
    Jeju_Korea("CJU", "Republic of", "Jeju, Korea"), 
    Jerez_de_La_Frontera("XRY", "Spain", "Jerez de La Frontera"), 
    Jersey("JER", "Channel Islands", "Jersey"), 
    Jiamusi("JMU", "China", "Jiamusi"), 
    Jijiga("JIJ", "Ethiopia", "Jijiga"), 
    Joensuu("JOE", "Finland", "Joensuu"), 
    Johannesburg("JNB", "South Africa", "Johannesburg"), 
    Johnstown_PA("JST", "USA", "Johnstown, PA"), 
    Johor_Bahru("JHB", "Malaysia", "Johor Bahru"), 
    Jonesboro_AR("JBR", "USA", "Jonesboro, AR"), 
    Jonkoping("JKG", "Sweden", "Jonkoping"), 
    Joplin_MO("JLN", "USA", "Joplin, MO"), 
    Juneau_AK("JNU", "USA", "Juneau, AK"), 
    Jyvaskyla("JYV", "Finland", "Jyvaskyla"), 
    Kabul("KBL", "Afghanistan", "Kabul"), 
    Kagoshima("KOJ", "Japan", "Kagoshima"), 
    Kahului_Maui_HI("OGG", "USA", "Kahului, Maui, HI"), 
    Kailua_Kona_HI("KOA", "USA", "Kailua-Kona, HI"), 
    Kaitaia("KAT", "New Zealand", "Kaitaia"), 
    Kajaani("KAJ", "Finland", "Kajaani"), 
    Kalamazoo_MI("AZO", "USA", "Kalamazoo, MI"), 
    Kalaupapa_Molokai_HI("LUP", "USA", "Kalaupapa, Molokai, HI"), 
    Kalgoorlie_WA("KGI", "Australia", "Kalgoorlie, WA"), 
    Kalibo("KLO", "Philippines", "Kalibo"), 
    Kaliningrad("KGD", "Russia", "Kaliningrad"), 
    Kalispell_MT("FCA", "USA", "Kalispell, MT"), 
    Kalmar("KLR", "Sweden", "Kalmar"), 
    Kamloops_BC("YKA", "Canada", "Kamloops, BC"),
    Kamuela_Hawaii("KOA", "USA", "Kamuela, Hawaii"), 
    Kansas_City_MO("MCI", "USA", "Kansas City, MO"), 
    Kaohsiung("KHH", "Taiwan", "Kaohsiung"), 
    Kapalua_Maui_HI("JHM", "USA", "Kapalua, Maui, HI"), 
    Karachi("KHI", "Pakistan", "Karachi"), 
    Karaganda("KGF", "Kazakhstan", "Karaganda"), 
    Karlstad("KSD", "Sweden", "Karlstad"), 
    Karratha_WA("KTA", "Australia", "Karratha, WA"), 
    Karup("KRP", "Denmark", "Karup"), 
    Kashi("KHG", "China", "Kashi"), 
    Kathmandu("KTM", "Nepal", "Kathmandu"), 
    Katowice("KTW", "Poland", "Katowice"), 
    Kearney_NE("EAR", "USA", "Kearney, NE"), 
    Kelowna_BC("YLW", "Canada", "Kelowna, BC"),
    Kenai_AK("ENA", "USA", "Kenai, AK"), 
    Kenora_ON("YQK", "Canada", "Kenora, ON"), 
    Kerikeri("KKE", "New Zealand", "Kerikeri"), 
    Ketchikan_AK("KTN", "USA", "Ketchikan, AK"), 
    Key_West_FL("EYW", "USA", "Key West, FL"), 
    Kharkov("HRK", "Ukraine", "Kharkov"), 
    Khartoum("KRT", "Sudan", "Khartoum"), 
    Khon_Kaen("KKC", "Thailand", "Khon Kaen"), 
    Kiel("KEL", "Germany", "Kiel"), 
    Kiev("KBP", "Ukraine", "Kiev"), 
    Kigali("KGL", "Rwanda", "Kigali"), 
    Killeen_TX("GRK", "USA", "Killeen, TX"), 
    King_Salmon_AK("AKN", "USA", "King Salmon, AK"), 
    Kingman_AZ("IGM", "USA", "Kingman, AZ"), 
    Kingscote_Kangaroo_Island_SA("KGC", "Australia", "Kingscote, Kangaroo Island, SA"), 
    Kingston("KIN", "Jamaica", "Kingston"), 
    Kingston_ON("YGK", "Canada", "Kingston, ON"),
    Kingstown("SVD", "St. Vincent", "Kingstown"), 
    Kinshasa("FIH", "Zaire", "Kinshasa"), 
    Kirksville_MO("IRK", "USA", "Kirksville, MO"), 
    Kirkwall_Orkney_Islands("KOI", "Scotland", "Kirkwall, Orkney Islands"), 
    Kiruna("KRN", "Sweden", "Kiruna"), 
    Kisangani("FKI", "Zaire", "Kisangani"), 
    Kittila("KTT", "Finland", "Kittila"), 
    Klagenfurt("KLU", "Austria", "Klagenfurt"), 
    Klamath_Falls_OR("LMT", "USA", "Klamath Falls, OR"), 
    Knoxville_TN("TYS", "USA", "Knoxville, TN"), 
    Kodiak_AK("ADQ", "USA", "Kodiak, AK"), 
    Koh_Samui("USM", "Thailand", "Koh Samui"), 
    Kokkola("KOK", "Finland", "Kokkola"), 
    Komatsu("KMQ", "Japan", "Komatsu"), 
    Koror("ROR", "Palau", "Koror"), 
    Kos("KGS", "Greece", "Kos"), 
    Kosrae("KSA", "Micronesia", "Kosrae"), 
    Kota_Bharu("KBR", "Malaysia", "Kota Bharu"), 
    Kota_Kinabalu_Sabah("BKI", "Malaysia", "Kota Kinabalu, Sabah"), 
    Krabi("KBV", "Thailand", "Krabi"), 
    Krakow("KRK", "Poland", "Krakow"), 
    Kralendijk("BON", "Bonaire", "Kralendijk"), 
    Kramfors("KRF", "Sweden", "Kramfors"), 
    Kristiansand("KRS", "Norway", "Kristiansand"), 
    Kristianstad("KID", "Sweden", "Kristianstad"), 
    Kuala_Lumpur("KUL", "Malaysia", "Kuala Lumpur"), 
    Kuala_Terengganu("TGG", "Malaysia", "Kuala Terengganu"), 
    Kuantan("KUA", "Malaysia", "Kuantan"), 
    Kuching_Sarawak("KCH", "Malaysia", "Kuching, Sarawak"), 
    Kumamoto("KMJ", "Japan", "Kumamoto"), 
    Kunming("KMG", "China", "Kunming"), 
    Kuopio("KUO", "Finland", "Kuopio"), 
    Kushiro("KUH", "Japan", "Kushiro"), 
    Kuwait("KWI", "Kuwait", "Kuwait"), 
    Kzyl_Orda("KZO", "Kazakhstan", "Kzyl Orda"), 
    La_Coruna("LCG", "Spain", "La Coruna"), 
    La_Crosse_WI("LSE", "USA", "La Crosse, WI"), 
    La_Paz1("LAP", "Mexico", "La Paz (Leon)"), 
    La_Paz2("LPB", "Bolivia", "La Paz (El Alto Intl)"), 
    La_Romana("LRM", "Dominican Republic", "La Romana"), 
    La_Serena("LSC", "Chile", "La Serena"), 
    Lafayette_LA("LFT", "USA", "Lafayette, LA"), 
    Lagos("LOS", "Nigeria", "Lagos"), 
    Lahad_Datu_Sabah("LDU", "Malaysia", "Lahad Datu, Sabah"), 
    Lahore("LHE", "Pakistan", "Lahore"), 
    Lake_Charles_LA("LCH", "USA", "Lake Charles, LA"), 
    Lake_Havasu_City_AZ("HII", "USA", "Lake Havasu City, AZ"), 
    Lamezia_Terme("SUF", "Italy", "Lamezia Terme"), 
    Lanai_City_Lanai_HI("LNY", "USA", "Lanai City, Lanai, HI"), 
    Lancaster_PA("LNS", "USA", "Lancaster, PA"), 
    Langkawi("LGK", "Malaysia", "Langkawi"), 
    Lannion("LAI", "France", "Lannion"), 
    Lansing_MI("LAN", "USA", "Lansing, MI"), 
    Lanzhou("LHW", "China", "Lanzhou"), 
    Laramie_WY("LAR", "USA", "Laramie, WY"), 
    Laredo_TX("LRD", "USA", "Laredo, TX"), 
    Larnaca("LCA", "Cyprus", "Larnaca"), 
    Las_Cruces_NM("LRU", "USA", "Las Cruces, NM"), 
    Las_Palmas_Grand_Canary_Island("LPA", "Canary Islands", "Las Palmas, Grand Canary Island"), 
    Las_Vegas_NV("LAS", "USA", "Las Vegas, NV"), 
    Latrobe_PA("LBE", "USA", "Latrobe, PA"), 
    Launceston_Tas("LST", "Australia", "Launceston, Tas"), 
    Laurel_MS("PIB", "USA", "Laurel, MS"), 
    Lawton_OK("LAW", "USA", "Lawton, OK"), 
    Lazaro_Cardenas("LZC", "Mexico", "Lazaro Cardenas"), 
    Le_Havre("LEH", "France", "Le Havre"), 
    Lebanon_NH("LEB", "USA", "Lebanon, NH"), 
    Leeds("LBA", "England", "Leeds"), 
    Legaspi("LGP", "Philippines", "Legaspi"), 
    Leipzig("LEJ", "Germany", "Leipzig"), 
    Leon1("BJX", "Mexico", "Leon (Del Bajio)"), 
    Leon2("LEN", "Spain", "Leon (Leon)"), 
    Lerwick_Shetland_Islands("LSI", "Scotland", "Lerwick, Shetland Islands"), 
    Lethbridge_AB("YQL", "Canada", "Lethbridge, AB"),
    Lewiston_ID("LWS", "USA", "Lewiston, ID"), 
    Lewiston_ME("LEW", "USA", "Lewiston, ME"), 
    Lewistown_MT("LWT", "USA", "Lewistown, MT"), 
    Lexington_KY("LEX", "USA", "Lexington, KY"), 
    Lhasa_Tibet("LXA", "China", "Lhasa, Tibet"), 
    Liberal_KS("LBL", "USA", "Liberal, KS"), 
    Liberia("LIR", "Costa Rica", "Liberia"), 
    Libreville("LBV", "Gabon", "Libreville"), 
    Lihue_Kauai_HI("LIH", "USA", "Lihue, Kauai, HI"), 
    Lijiang_City("LJG", "China", "Lijiang City"), 
    Lille("LIL", "France", "Lille"), 
    Lilongwe("LLW", "Malawi", "Lilongwe"), 
    Lima("LIM", "Peru", "Lima"), 
    Limoges("LIG", "France", "Limoges"), 
    Lincang("LNJ", "China", "Lincang"), 
    Lincoln_NE("LNK", "USA", "Lincoln, NE"), 
    Linkoping("LPI", "Sweden", "Linkoping"), 
    Linz("LNZ", "Austria", "Linz"), 
    Lisbon("LIS", "Portugal", "Lisbon"), 
    Little_Rock_AR("LIT", "USA", "Little Rock, AR"), 
    Liverpool("LPL", "England", "Liverpool"), 
    Ljubljana("LJU", "Slovenia", "Ljubljana"), 
    Logrono("RJL", "Spain", "Logrono"), 
    Lome("LFW", "Togo", "Lome"), 
    London1("LCY", "England", "London (London City)"), 
    London2("LGW", "England", "London (Gatwick)"), 
    London3("LHR", "England", "London (Heathrow)"), 
    London4("LON", "England", "London"), 
    London5("STN", "England", "London (Stansted)"), 
    London_ON("YXU", "Canada", "London, ON"),
    Londonderry("LDY", "Northern Ireland", "Londonderry"), 
    Long_Banga("LBP", "Malaysia", "Long Banga"), 
    Long_Beach_CA("LGB", "USA", "Long Beach, CA"), 
    Longreach_QLD("LRE", "Australia", "Longreach, Qld"), 
    Longview_TX("GGG", "USA", "Longview, TX"), 
    Longyearbyen_Svalbard("LYR", "Norway", "Longyearbyen, Svalbard"), 
    Loreto("LTO", "Mexico", "Loreto"), 
    Lorient("LRT", "France", "Lorient"), 
    Los_Angeles_CA("LAX", "USA", "Los Angeles, CA"),
    Los_Cabos("SJD", "Mexico", "Los Cabos"), 
    Louisville_KY_USA("SDF", "USA", "Louisville, KY, USA"), 
    Lourdes("LDE", "France", "Lourdes"), 
    Luanda("LAD", "Angola", "Luanda"), 
    Lubbock_TX("LBB", "USA", "Lubbock, TX"), 
    Lubumbashi("FBM", "Zaire", "Lubumbashi"), 
    Lugano("LUG", "Switzerland", "Lugano"), 
    Lugansk("VSG", "Ukraine", "Lugansk"), 
    Lukla("LUA", "Nepal", "Lukla"), 
    Lulea("LLA", "Sweden", "Lulea"), 
    Lusaka("LUN", "Zambia", "Lusaka"), 
    Luton("LTN", "England", "Luton"), 
    Luxembourg("LUX", "Luxembourg", "Luxembourg"), 
    Luxor("LXR", "Egypt", "Luxor"), 
    Lycksele("LYC", "Sweden", "Lycksele"), 
    Lynchburg_VA("LYH", "USA", "Lynchburg, VA"), 
    Lyon("LYS", "France", "Lyon"), 
    Mackay_QLD("MKY", "Australia", "Mackay, Qld"), 
    Macon_GA("MCN", "USA", "Macon, GA"), 
    Madison_WI("MSN", "USA", "Madison, WI"), 
    Madrid("MAD", "Spain", "Madrid"), 
    Mae_Hong_Son("HGN", "Thailand", "Mae Hong Son"), 
    Magdalens_Islands_PQ("", "", "Magdalens Islands, PQ"), 
    Mahebourg("MRU", "Mauritius", "Mahebourg"), 
    Majuro("MAJ", "Marshall Islands", "Majuro"), 
    Mala_Mala("AAM", "South Africa", "Mala Mala"), 
    Malabo_Bioko_Island("SSG", "Equatorial Guinea", "Malabo, Bioko Island"), 
    Malaga("AGP", "Spain", "Malaga"), 
    Male("MLE", "Maldives", "Male"),
    Malmo("MMX", "Sweden", "Malmo"), 
    Managua("MGA", "Nicaragua", "Managua"), 
    Manama("BAH", "Bahrain", "Manama"), 
    Manaus("MAO", "Brazil", "Manaus"), 
    Manchester("MAN", "England", "Manchester"), 
    Manchester_NH("MHT", "USA", "Manchester, NH"), 
    Mangrove_Cay_Andros_Island("MAY", "Bahamas", "Mangrove Cay, Andros Island"), 
    Manhattan_KS("MHK", "USA", "Manhattan, KS"), 
    Manila("MNL", "Philippines", "Manila"), 
    Manistee_MI("MBL", "USA", "Manistee, MI"), 
    Manzanillo("ZLO", "Mexico", "Manzanillo"), 
    Manzini("MTS", "Swaziland", "Manzini"), 
    Mao_Minorca("MAH", "Spain", "Mao, Minorca"), 
    Maputo("MPM", "Mozambique", "Maputo"), 
    Maracaibo("MAR", "Venezuela", "Maracaibo"), 
    Mariehamn_Aland("MHQ", "Finland", "Mariehamn, Aland"), 
    Marilia("MII", "Brazil", "Marilia"), 
    Marion_IL("MWA", "USA", "Marion, IL"), 
    Mariupol("MPW", "Ukraine", "Mariupol"), 
    Maroochydore_QLD("MCY", "Australia", "Maroochydore, Qld"), 
    Marquette_MI("MQT", "USA", "Marquette, MI"), 
    Marrakech("RAK", "Morocco", "Marrakech"),
    Marseille("MRS", "France", "Marseille"), 
    Marsh_Harbour_Abaco_Island("MHH", "Bahamas", "Marsh Harbour, Abaco Island"), 
    Marthas_Vineyard_MA("MVY", "USA", "Martha's Vineyard, MA"), 
    Maseru("MSU", "Lesotho", "Maseru"), 
    Mason_City_IA("MCW", "USA", "Mason City, IA"), 
    Massena_NY("MSS", "USA", "Massena, NY"), 
    Matsu("MFK", "Taiwan", "Matsu"), 
    Matsuyama("MYJ", "Japan", "Matsuyama"), 
    Mazatlan("MZT", "Mexico", "Mazatlan"), 
    McAllen_TX("MFE", "USA", "McAllen, TX"), 
    McCook_NE("MCK", "USA", "McCook, NE"), 
    Medan_Sumatra("MES", "Indonesia", "Medan, Sumatra"), 
    Medellin("MDE", "Colombia", "Medellin"), 
    Medford_OR("MFR", "USA", "Medford, OR"), 
    Medicine_Hat_AB("YXH", "Canada", "Medicine Hat, AB"),
    Melbourne_FL("MLB", "USA", "Melbourne, FL"), 
    Melbourne_VIC1("AVV", "Australia", "Melbourne, Vic (Avalon)"), 
    Melbourne_VIC2("MEL", "Australia", "Melbourne, Vic"),
    Melilla("MLN", "Spain", "Melilla"), 
    Memanbetsu("MMB", "Japan", "Memanbetsu"), 
    Memphis_TN("MEM", "USA", "Memphis, TN"), 
    Mendoza("MDZ", "Argentina", "Mendoza"), 
    Merida("MID", "Mexico", "Merida"), 
    Meridian_MS("MEI", "USA", "Meridian, MS"), 
    Merimbula_NSW("MIM", "Australia", "Merimbula, NSW"), 
    Metz("ETZ", "France", "Metz"), 
    Mexicali("MXL", "Mexico", "Mexicali"), 
    Mexico_City("MEX", "Mexico", "Mexico City"), 
    Miami_FL("MIA", "USA", "Miami, FL"), 
    Mian_Yang("MIG", "China", "Mian Yang"), 
    Midland_TX("MAF", "USA", "Midland, TX"), 
    Mikonos("JMK", "Greece", "Mikonos"), 
    Milan1("LIN", "Italy", "Milan (Linate)"), 
    Milan2("MIL", "Italy", "Milan"), 
    Milan3("MXP", "Italy", "Milan (Malpensa)"), 
    Mildura_VIC("MQL", "Australia", "Mildura, Vic"), 
    Miles_City_MT("MLS", "USA", "Miles City, MT"), 
    Milwaukee_WI("MKE", "USA", "Milwaukee, WI"), 
    Minneapolis_MN("MSP", "USA", "Minneapolis, MN"), 
    Minot_ND("MOT", "USA", "Minot, ND"), 
    Minsk1("MHP", "Belarus", "Minsk (Intl 1)"), 
    Minsk2("MSQ", "Belarus", "Minsk (Intl 2)"), 
    Miri_Sarawak("MYY", "Malaysia", "Miri, Sarawak"), 
    Misawa("MSJ", "Japan", "Misawa"), 
    Missoula_MT("MSO", "USA", "Missoula, MT"), 
    Miyazaki("KMI", "Japan", "Miyazaki"), 
    Mobile_AL("MOB", "USA", "Mobile, AL"), 
    Modesto_CA("MOD", "USA", "Modesto, CA"), 
    Mogadishu("MGQ", "Somalia", "Mogadishu"), 
    Moline_IL("MLI", "USA", "Moline, IL"), 
    Mombasa("MBA", "Kenya", "Mombasa"), 
    Monastir("MIR", "Tunisia", "Monastir"), 
    Monclova("LOV", "Mexico", "Monclova"), 
    Moncton_NB("YQM", "Canada", "Moncton, NB"),
    Monroe_LA("MLU", "USA", "Monroe, LA"), 
    Monrovia("ROB", "Liberia", "Monrovia"), 
    Mont_Joli_QC("YYY", "Canada", "Mont-Joli, QC"),
    Montego_Bay("MBJ", "Jamaica", "Montego Bay"), 
    Monterey_CA("MRY", "USA", "Monterey, CA"), 
    Monterrey("MTY", "Mexico", "Monterrey"), 
    Montevideo("MVD", "Uruguay", "Montevideo"), 
    Montgomery_AL("MGM", "USA", "Montgomery, AL"), 
    Montpellier("MPL", "France", "Montpellier"),
    Montreal_QC("YUL", "Canada", "Montreal, QC"), 
    Montrose_CO("MTJ", "USA", "Montrose, CO"), 
    Mora("MXX", "Sweden", "Mora"), 
    Moree_NSW("MRZ", "Australia", "Moree, NSW"), 
    Morelia("MLM", "Mexico", "Morelia"), 
    Morgantown_WV("MGW", "USA", "Morgantown, WV"), 
    Moroni("HAH", "Comoro Islands", "Moroni"), 
    Moruya_NSW("MYA", "Australia", "Moruya, NSW"), 
    Moscow1("MOW", "Russia", "Moscow"), 
    Moscow2("SVO", "Russia", "Moscow (Sheremetyevo)"), 
    Moscow3("VKO", "Russia", "Moscow (Vnukovo)"), 
    Moses_Lake_WA("MWH", "USA", "Moses Lake, WA"), 
    Mount_Gambier_SA("MGB", "Australia", "Mount Gambier, SA"), 
    Mount_Isa_QLD("ISA", "Australia", "Mount Isa, Qld"), 
    Mudanjiang("MDG", "China", "Mudanjiang"), 
    Mulu("MZV", "Malaysia", "Mulu"), 
    Mumbai("BOM", "India", "Mumbai (Bombay)"), 
    Munich("MUC", "Germany", "Munich"), 
    Munster("FMO", "Germany", "Munster"), 
    Murcia("MJV", "Spain", "Murcia"), 
    Murmansk("MMK", "Russia", "Murmansk"), 
    Muscat("MCT", "Oman", "Muscat"), 
    Muscle_Shoals_AL("MSL", "USA", "Muscle Shoals, AL"), 
    Muskegon_MI("MKG", "USA", "Muskegon, MI"), 
    Myrtle_Beach_SC("MYR", "USA", "Myrtle Beach, SC"), 
    Mytilene_Lesbos_Island("MJT", "Greece", "Mytilene, Lesbos Island"), 
    NDjamena("NDJ", "Chad", "N'Djamena"), 
    Nadi("NAN", "Fiji", "Nadi"), 
    Nador("NDR", "Morocco", "Nador"), 
    Nagasaki("NGS", "Japan", "Nagasaki"), 
    Nagoya("NGO", "Japan", "Nagoya"),
    Naha_Okinawa("OKA", "Japan", "Naha, Okinawa"), 
    Nairobi("NBO", "Kenya", "Nairobi"), 
    Nakhon_Si_Thammarat("NST", "Thailand", "Nakhon Si Thammarat"), 
    Nanaimo_BC("YCD", "Canada", "Nanaimo, BC"), 
    Nanchang("KHN", "China", "Nanchang"), 
    Nangen("LZN", "Taiwan", "Nangen"), 
    Nanjing("NKG", "China", "Nanjing"), 
    Nanki_Shirahama("SHM", "Japan", "Nanki Shirahama"), 
    Nanning("NNG", "China", "Nanning"), 
    Nantes("NTE", "France", "Nantes"), 
    Nantucket_MA("ACK", "USA", "Nantucket, MA"), 
    Napier("NPE", "New Zealand", "Napier"), 
    Naples("NAP", "Italy", "Naples"), 
    Naples_FL("APF", "USA", "Naples, FL"), 
    Narrabri_NSW("NAA", "Australia", "Narrabri, NSW"), 
    Narrandera_NSW("NRA", "Australia", "Narrandera, NSW"), 
    Narvik("NVK", "Norway", "Narvik"), 
    Naryan_Mar("NNM", "Russia", "Naryan Mar"), 
    Nashville_TN("BNA", "USA", "Nashville, TN"), 
    Nassau1("NAS", "Bahamas", "Nassau (Intl)"), 
    Nassau2("PID", "Bahamas", "Nassau (Paradise Island)"), 
    Naze_Amami_O_Island("ASJ", "Japan", "Naze, Amami-O Island"), 
    Nelson("NSN", "New Zealand", "Nelson"), 
    Nelspruit("MQP", "South Africa", "Nelspruit"), 
    New_Bern_NC("EWN", "USA", "New Bern, NC"), 
    New_Haven_CT("HVN", "USA", "New Haven, CT"), 
    New_Orleans_LA("MSY", "USA", "New Orleans, LA"), 
    New_York_NY1("JFK", "USA", "New York, NY (John F. Kennedy)"), 
    New_York_NY2("LGA", "USA", "New York, NY (LaGuardia)"), 
    New_York_NY3("NYC", "USA", "New York, NY"), 
    Newark_NJ("EWR", "USA", "Newark, NJ"), 
    Newburgh_NY("SWF", "USA", "Newburgh, NY"), 
    Newcastle("NCL", "England", "Newcastle"), 
    Newcastle_NSW("NTL", "Australia", "Newcastle, NSW"), 
    Newman_WA("ZNE", "Australia", "Newman, WA"), 
    Newport_News_VA("PHF", "USA", "Newport News, VA"), 
    Niamey("NIM", "Niger", "Niamey"), 
    Nice("NCE", "France", "Nice"), 
    Niigata("KIJ", "Japan", "Niigata"), 
    Ningbo("NGB", "China", "Ningbo"), 
    Nizhniy_Novgorod("GOJ", "Russia", "Nizhniy Novgorod"), 
    Nome_AK("OME", "USA", "Nome, AK"), 
    Norfolk_VA("ORF", "USA", "Norfolk, VA"), 
    Norrkoping("NRK", "Sweden", "Norrkoping"), 
    North_Bay_ON("YYB", "Canada", "North Bay, ON"),
    North_Bend_OR("OTH", "USA", "North Bend, OR"), 
    North_Eleuthera("ELH", "Bahamas", "North Eleuthera"), 
    North_Platte_NE("LBF", "USA", "North Platte, NE"), 
    Norwich("NWI", "England", "Norwich"), 
    Nouakchott("NKC", "Mauritania", "Nouakchott"), 
    Noumea1("GEA", "New Caledonia", "Noumea (Magenta)"), 
    Noumea2("NOU", "New Caledonia", "Noumea (Tontouta)"), 
    Novosibirsk_Siberia("OVB", "Russia", "Novosibirsk, Siberia"), 
    Nuevo_Laredo("NLD", "Mexico", "Nuevo Laredo"), 
    Nuremberg("NUE", "Germany", "Nuremberg"), 
    Oakland_CA("OAK", "USA", "Oakland, CA"), 
    Oaxaca("OAX", "Mexico", "Oaxaca"), 
    Obihiro("OBO", "Japan", "Obihiro"), 
    Ocho_Rios("OCJ", "Jamaica", "Ocho Rios"), 
    Odate_Noshiro("ONJ", "Japan", "Odate Noshiro"), 
    Odessa("ODS", "Ukraine", "Odessa"), 
    Ogdensburg_NY("OGS", "USA", "Ogdensburg, NY"), 
    Oita("OIT", "Japan", "Oita"), 
    Oklahoma_City_OK("OKC", "USA", "Oklahoma City, OK"), 
    Olbia_Sardinia("OLB", "Italy", "Olbia, Sardinia"), 
    Olympic_Dam_SA("OLP", "Australia", "Olympic Dam, SA"), 
    Omaha_NE("OMA", "USA", "Omaha, NE"), 
    Omsk_Siberia("OMS", "Russia", "Omsk, Siberia"), 
    Ontario_CA("ONT", "USA", "Ontario, CA"), 
    Orange_County_CA("SNA", "USA", "Orange County, CA"), 
    Orange_NSW("OAG", "Australia", "Orange, NSW"), 
    Oranjestad1("AUA", "Aruba", "Oranjestad (Reina Beatrix)"), 
    Oranjestad2("EUX", "St. Eustatius", "Oranjestad (F.D. Roosevelt)"), 
    Orebro("ORB", "Sweden", "Orebro"), 
    Orlando_FL("MCO", "USA", "Orlando, FL"), 
    Ornskoldsvik("OER", "Sweden", "Ornskoldsvik"), 
    Osaka1("ITM", "Japan", "Osaka (Itami)"), 
    Osaka2("KIX", "Japan", "Osaka (Kansai)"), 
    Osaka3("OSA", "Japan", "Osaka"), 
    Oshkosh_WI("OSH", "USA", "Oshkosh, WI"), 
    Oslo("OSL", "Norway", "Oslo"), 
    Osorno("ZOS", "Chile", "Osorno"), 
    Ostersund("OSD", "Sweden", "Ostersund"), 
    Ostrava("OSR", "Czech Republic", "Ostrava"), 
    Ottawa_ON("YOW", "Canada", "Ottawa, ON"),
    Ouagadougou("OUA", "Burkina Faso", "Ouagadougou"), 
    Oulu("OUL", "Finland", "Oulu"), 
    Owensboro_KY("OWB", "USA", "Owensboro, KY"), 
    Oxnard_CA("OXR", "USA", "Oxnard, CA"), 
    Paderborn("PAD", "Germany", "Paderborn"), 
    Paducah_KY("PAH", "USA", "Paducah, KY"), 
    Page_AZ("PGA", "USA", "Page, AZ"), 
    Pago_Pago_Tutuila("PPG", "American Samoa", "Pago Pago, Tutuila"), 
    Pajala("PJA", "Sweden", "Pajala"), 
    Palembang_Sumatra("PLM", "Indonesia", "Palembang, Sumatra"), 
    Palermo_Sicily("PMO", "Italy", "Palermo, Sicily"), 
    Palm_Springs_CA("PSP", "USA", "Palm Springs, CA"), 
    Palma_Mallorca("PMI", "Spain", "Palma, Mallorca"), 
    Palmas("PMW", "Brazil", "Palmas"), 
    Palmerston_North("PMR", "New Zealand", "Palmerston North"), 
    Pamplona("PNA", "Spain", "Pamplona"), 
    Panama_City("PTY", "Panama", "Panama City"), 
    Panama_City_FL("PFN", "USA", "Panama City, FL"), 
    Papeete_Tahiti("PPT", "French Polynesia", "Papeete, Tahiti"), 
    Paphos("PFO", "Cyprus", "Paphos"), 
    Paraburdoo_WA("PBO", "Australia", "Paraburdoo, WA"), 
    Paramaribo("PBM", "Suriname", "Paramaribo"), 
    Paris1("CDG", "France", "Paris (Charles-De-Gaulle)"), 
    Paris2("ORY", "France", "Paris (Orly)"), 
    Paris3("PAR", "France", "Paris"), 
    Parkersburg_WV("PKB", "USA", "Parkersburg, WV"), 
    Parkes_NSW("PKE", "Australia", "Parkes, NSW"), 
    Pasco_WA("PSC", "USA", "Pasco, WA"), 
    Pau("PUF", "France", "Pau"), 
    Pellston_MI("PLN", "USA", "Pellston, MI"), 
    Penang_Penang_Island("PEN", "Malaysia", "Penang, Penang Island"), 
    Pendleton_OR("PDT", "USA", "Pendleton, OR"), 
    Pensacola_FL("PNS", "USA", "Pensacola, FL"), 
    Penticton_BC("YYF", "Canada", "Penticton, BC"),
    Peoria_IL("PIA", "USA", "Peoria, IL"), 
    Perpignan("PGF", "France", "Perpignan"), 
    Perth_WA("PER", "Australia", "Perth, WA"), 
    Perugia("PEG", "Italy", "Perugia"), 
    Peshawar("PEW", "Pakistan", "Peshawar"), 
    Petropavlovsk_Kamchatsky_Siberia("PKC", "Russia", "Petropavlovsk-Kamchatsky, Siberia"), 
    Philadelphia_PA("PHL", "USA", "Philadelphia, PA"), 
    Philipsburg("SXM", "St. Maarten", "Philipsburg"), 
    Phitsanulok("PHS", "Thailand", "Phitsanulok"), 
    Phnom_Penh("PNH", "Cambodia", "Phnom Penh"), 
    Phoenix_AZ("PHX", "USA", "Phoenix, AZ"), 
    Phuket("HKT", "Thailand", "Phuket"), 
    Piedras_Negras("PDS", "Mexico", "Piedras Negras"), 
    Pierre_SD("PIR", "USA", "Pierre, SD"), 
    Pinehurst_NC("SOP", "USA", "Pinehurst, NC"), 
    Pisa("PSA", "Italy", "Pisa"), 
    Pittsburgh_PA("PIT", "USA", "Pittsburgh, PA"), 
    Placencia("PLJ", "Belize", "Placencia"), 
    Plattsburgh_NY("PLB", "USA", "Plattsburgh, NY"), 
    Pleiku("PXU", "Vietnam", "Pleiku"), 
    Pocatello_ID("PIH", "USA", "Pocatello, ID"), 
    Pohnpei("PNI", "Micronesia", "Pohnpei"), 
    Pointe_A_Pitre_Grande_Terre("PTP", "Guadeloupe", "Pointe-A-Pitre, Grande-Terre"), 
    Ponca_City_OK("PNC", "USA", "Ponca City, OK"), 
    Ponta_Delgada_Sao_Miguel_Island("PDL", "Azores", "Ponta Delgada, Sao Miguel Island"), 
    Port_Hardy_BC("YZT", "Canada", "Port Hardy, BC"),
    Port_Hedland_WA("PHE", "Australia", "Port Hedland, WA"), 
    Port_Lincoln_SA("PLO", "Australia", "Port Lincoln, SA"), 
    Port_Macquarie_NSW("PQQ", "Australia", "Port Macquarie, NSW"), 
    Port_Moresby("POM", "Papua-New Guinea", "Port Moresby"), 
    Port_of_Spain("POS", "Trinidad and Tobago", "Port of Spain"), 
    Port_Vila_Efate_Island("VLI", "Vanuatu", "Port Vila, Efate Island"), 
    Port_au_Prince("PAP", "Haiti", "Port-au-Prince"), 
    Portland_ME("PWM", "USA", "Portland, ME"), 
    Portland_OR("PDX", "USA", "Portland, OR"), 
    Portland_VIC("PTJ", "Australia", "Portland, Vic"), 
    Porto("OPO", "Portugal", "Porto"), 
    Porto_Alegre("POA", "Brazil", "Porto Alegre"), 
    Porto_Santo("PXO", "Madeira", "Porto Santo"), 
    Portsmouth_NH("PSM", "USA", "Portsmouth, NH"), 
    Powell_River_BC("YPW", "Canada", "Powell River, BC"),
    Poznan("POZ", "Poland", "Poznan"), 
    Prague("PRG", "Czech Republic", "Prague"), 
    Prescott_AZ("PRC", "USA", "Prescott, AZ"), 
    Presque_Isle_ME("PQI", "USA", "Presque Isle, ME"), 
    Prince_George_BC("YXS", "Canada", "Prince George, BC"),
    Prince_Rupert_BC("YPR", "Canada", "Prince Rupert, BC"),
    Proserpine_QLD("PPP", "Australia", "Proserpine, Qld"), 
    Providence_RI("PVD", "USA", "Providence, RI"), 
    Providenciales_Island("PLS", "Turks and Caicos Islands", "Providenciales Island"), 
    Provincetown_MA("PVC", "USA", "Provincetown, MA"), 
    Pucon("ZPC", "Chile", "Pucon"), 
    Puebla("PBC", "Mexico", "Puebla"), 
    Pueblo_CO("PUB", "USA", "Pueblo, CO"), 
    Puerto_del_Rosario_Fuerteventura_Island("FUE", "Canary Islands", "Puerto del Rosario, Fuerteventura Island"), 
    Puerto_Escondido("PXM", "Mexico", "Puerto Escondido"), 
    Puerto_Montt("PMC", "Chile", "Puerto Montt"), 
    Puerto_Plata("POP", "Dominican Republic", "Puerto Plata"), 
    Puerto_Princesa("PPS", "Philippines", "Puerto Princesa"), 
    Puerto_Vallarta("PVR", "Mexico", "Puerto Vallarta"), 
    Pullman_WA("PUW", "USA", "Pullman, WA"), 
    Punta_Arenas_Tierra_del_Fuego("PUQ", "Chile", "Punta Arenas, Tierra del Fuego"), 
    Punta_Cana("PUJ", "Dominican Republic", "Punta Cana"), 
    Punta_Gorda("PND", "Belize", "Punta Gorda"), 
    Puttaparthi("PUT", "India", "Puttaparthi"), 
    Pyongyang("FNJ", "North Korea", "Pyongyang"), 
    Qingdao("TAO", "China", "Qingdao"), 
    Quebec_QC("YQB", "Canada", "Quebec City, QC"),
    Queenstown("ZQN", "New Zealand", "Queenstown"), 
    Queretaro("QRO", "Mexico", "Queretaro"), 
    Quesnel_BC("YQZ", "Canada", "Quesnel, BC"),
    Quimper("UIP", "France", "Quimper"), 
    Quincy_IL("UIN", "USA", "Quincy, IL"), 
    Quito("UIO", "Ecuador", "Quito"), 
    Rach_Gia("VKG", "Vietnam", "Rach Gia"), 
    Raleigh_NC("RDU", "USA", "Raleigh, NC"), 
    Rangoon("RGN", "Myanmar (Burma)", "Rangoon"), 
    Rankin_Inlet_NT("YRT", "Canada", "Rankin Inlet, NT"),
    Ranong("UNN", "Thailand", "Ranong"), 
    Rapid_City_SD("RAP", "USA", "Rapid City, SD"), 
    Recife("REC", "Brazil", "Recife"), 
    Red_Lake_ON("YRL", "Canada", "Red Lake, ON"),
    Redding_CA("RDD", "USA", "Redding, CA"), 
    Redmond_OR("RDM", "USA", "Redmond, OR"), 
    Reggio_di_Calabria("REG", "Italy", "Reggio di Calabria"), 
    Regina_SK("YQR", "Canada", "Regina, SK"),
    Rennes("RNS", "France", "Rennes"), 
    Reno_NV("RNO", "USA", "Reno, NV"), 
    Reykjavik1("KEF", "Iceland", "Reykjavik (Intl)"), 
    Reykjavik2("REK", "Iceland", "Reykjavik"), 
    Reykjavik3("RKV", "Iceland", "Reykjavik (Domestic)"), 
    Reynosa("REX", "Mexico", "Reynosa"), 
    Rhinelander_WI("RHI", "USA", "Rhinelander, WI"), 
    Rhodes("RHO", "Greece", "Rhodes"), 
    Richmond_VA("RIC", "USA", "Richmond, VA"), 
    Riga("RIX", "Latvia", "Riga"), 
    Rimini("RMI", "Italy", "Rimini"), 
    Rio_de_Janeiro1("GIG", "Brazil", "Rio de Janeiro (Galeao)"), 
    Rio_de_Janeiro2("RIO", "Brazil", "Rio de Janeiro"), 
    Rio_de_Janeiro3("SDU", "Brazil", "Rio de Janeiro (Santos Dumont)"), 
    Riverton_WY("RIW", "USA", "Riverton, WY"), 
    Riyadh("RUH", "Saudi Arabia", "Riyadh"), 
    Roanoke_VA("ROA", "USA", "Roanoke, VA"), 
    Roberval_QC("YRJ", "Canada", "Roberval, QC"),
    Rochester_MN("RST", "USA", "Rochester, MN"), 
    Rochester_NY("ROC", "USA", "Rochester, NY"), 
    Rock_Sound("RSD", "Bahamas", "Rock Sound"), 
    Rock_Springs_WY("RKS", "USA", "Rock Springs, WY"), 
    Rockford_IL("RFD", "USA", "Rockford, IL"), 
    Rockhampton_QLD("ROK", "Australia", "Rockhampton, Qld"), 
    Rockland_ME("RKD", "USA", "Rockland, ME"), 
    Rodez("RDZ", "France", "Rodez"), 
    Roma_QLD("RMA", "Australia", "Roma, Qld"), 
    Rome1("CIA", "Italy", "Rome (Ciampino)"), 
    Rome2("FCO", "Italy", "Rome (Leonardo da Vinci-Fiumicino)"), 
    Rome3("ROM", "Italy", "Rome"), 
    Ronne("RNN", "Denmark", "Ronne"), 
    Ronneby("RNB", "Sweden", "Ronneby"), 
    Roseau("DOM", "Dominica", "Roseau"), 
    Rostov("ROV", "Russia", "Rostov"), 
    Roswell_NM("ROW", "USA", "Roswell, NM"), 
    Rotorua("ROT", "New Zealand", "Rotorua"), 
    Rotterdam("RTM", "Netherlands", "Rotterdam"), 
    Rouen("URO", "France", "Rouen"), 
    Rouyn_Noranda_QC("YUY", "Canada", "Rouyn-Noranda, QC"),
    Rovaniemi("RVN", "Finland", "Rovaniemi"), 
    Roxas_City("RXS", "Philippines", "Roxas City"), 
    Rutland_VT("RUT", "USA", "Rutland, VT"), 
    Rzeszow("RZE", "Poland", "Rzeszow"), 
    Saba_Island("SAB", "Saba", "Saba Island"), 
    Sacramento_CA("SMF", "USA", "Sacramento, CA"), 
    Saga("HSG", "Japan", "Saga"), 
    Saginaw_MI("MBS", "USA", "Saginaw, MI"), 
    Saint_John_NB("YSJ", "Canada", "Saint John, NB"),
    Saint_Denis("RUN", "Reunion", "Saint-Denis"), 
    Saint_Pierre("ZSE", "Reunion", "Saint-Pierre"), 
    Saipan("SPN", "Northern Mariana Islands", "Saipan"), 
    Salina_KS("SLN", "USA", "Salina, KS"), 
    Salisbury_MD("SBY", "USA", "Salisbury, MD"), 
    Salt_Lake_City_UT("SLC", "USA", "Salt Lake City, UT"), 
    Saltillo("SLW", "Mexico", "Saltillo"), 
    Salvador("SSA", "Brazil", "Salvador"), 
    Salzburg("SZG", "Austria", "Salzburg"), 
    Samsun("SZF", "Turkey", "Samsun"), 
    San_Andres("ADZ", "Colombia", "San Andres"), 
    San_Andros("SAQ", "Bahamas", "San Andros"), 
    San_Angelo_TX("SJT", "USA", "San Angelo, TX"), 
    San_Antonio_TX("SAT", "USA", "San Antonio, TX"), 
    San_Carlos_de_Bariloche("BRC", "Argentina", "San Carlos de Bariloche"), 
    San_Diego_CA("SAN", "USA", "San Diego, CA"), 
    Setif("QSF", "Algeria", "Setif, Algeria"), 
    San_Francisco_CA("SFO", "USA", "San Francisco, CA"), 
    San_Jose("SJO", "Costa Rica", "San Jose"), 
    San_Jose_CA("SJC", "USA", "San Jose, CA"), 
    San_Juan("SJU", "Puerto Rico", "San Juan"), 
    San_Luis_Obispo_CA("SBP", "USA", "San Luis Obispo, CA"), 
    San_Luis_Potosi("SLP", "Mexico", "San Luis Potosi"), 
    San_Salvador("SAL", "El Salvador", "San Salvador"), 
    San_Sebastian("EAS", "Spain", "San Sebastian"), 
    Sanaa("SAH", "Yemen", "Sanaa"), 
    Sand_Point_AK("SDP", "USA", "Sand Point, AK"), 
    Sandakan_Sabah("SDK", "Malaysia", "Sandakan, Sabah"), 
    Sandefjord("TRF", "Norway", "Sandefjord"), 
    Sandspit_Queen_Charlotte_Islands_BC("YZP", "Canada", "Sandspit, Queen Charlotte Islands, BC"),
    Santa_Barbara_CA("SBA", "USA", "Santa Barbara, CA"), 
    Santa_Cruz("SPC", "Spain", "Santa Cruz"), 
    Santa_Cruz_de_Tenerife("TFN", "Canary Islands", "Santa Cruz de Tenerife"), 
    Santa_Fe_NM("SAF", "USA", "Santa Fe, NM"), 
    Santa_Maria_CA("SMX", "USA", "Santa Maria, CA"), 
    Santa_Maria_Sal_Island("SID", "Cape Verde", "Santa Maria, Sal Island"), 
    Santa_Rosa("RSA", "Argentina", "Santa Rosa"), 
    Santa_Rosa_CA("STS", "USA", "Santa Rosa, CA"), 
    Santander("SDR", "Spain", "Santander"), 
    Santiago1("SCL", "Chile", "Santiago"), 
    Santiago2("STI", "Dominican Republic", "Santiago"), 
    Santo_Domingo("SDQ", "Dominican Republic", "Santo Domingo"), 
    Sanya("SYX", "China", "Sanya"), 
    Sao_Jose_So_Rio_Preto("SJP", "Brazil", "Sao Jose So Rio Preto"), 
    Sao_Paulo1("CGH", "Brazil", "Sao Paulo (Congonhas)"), 
    Sao_Paulo2("GRU", "Brazil", "Sao Paulo (Guarulhos)"), 
    Sao_Paulo3("SAO", "Brazil", "Sao Paulo"), 
    Sapporo1("CTS", "Japan", "Sapporo"), 
    Sapporo2("OKD", "Japan", "Sapporo (Okadama)"), 
    Sarajevo("SJJ", "Bosnia and Herzegovina", "Sarajevo"), 
    Saranac_Lake_NY("SLK", "USA", "Saranac Lake, NY"), 
    Sarasota_FL("SRQ", "USA", "Sarasota, FL"), 
    Sarnia_ON("YZR", "Canada", "Sarnia, ON"), 
    Saskatoon_SK("YXE", "Canada", "Saskatoon, SK"),
    Sault_Ste_Marie_MI("CIU", "USA", "Sault Ste. Marie, MI"), 
    Sault_Ste_Marie_ON("YAM", "Canada", "Sault Ste. Marie, ON"),
    Savannah_GA("SAV", "USA", "Savannah, GA"), 
    Scottsbluff_NE("BFF", "USA", "Scottsbluff, NE"), 
    Seattle_WA("SEA", "USA", "Seattle, WA"), 
    Semipalatinsk("PLX", "Kazakhstan", "Semipalatinsk"), 
    Seoul("GMP", "South Korea", "Seoul, South Korea"), 
    Incheon("ICN", "South Korea", "Incheon, South Korea"), 
    Sept_Iles_QC("YZV", "Canada", "Sept-Iles, QC"), 
    Seville("SVQ", "Spain", "Seville"), 
    Shanghai1("PVG", "China", "Shanghai (Pudong)"), 
    Shanghai2("SHA", "China", "Shanghai"), 
    Shannon("SNN", "Ireland", "Shannon"), 
    Shantou("SWA", "China", "Shantou"), 
    Sharjah("SHJ", "United Arab Emirates", "Sharjah"), 
    Sharm_El_Sheikh("SSH", "Egypt", "Sharm El Sheikh"), 
    Shenandoah_Valley_Airport_VA("SHD", "USA", "Shenandoah Valley Airport, VA"), 
    Shenyang("SHE", "China", "Shenyang"), 
    Shenzhen("SZX", "China", "Shenzhen"), 
    Sheridan_WY("SHR", "USA", "Sheridan, WY"), 
    Shijiazhuang("SJW", "China", "Shijiazhuang"), 
    Shreveport_LA("SHV", "USA", "Shreveport, LA"), 
    Sibu_Sarawak("SBW", "Malaysia", "Sibu, Sarawak"), 
    Sidney_MT("SDY", "USA", "Sidney, MT"), 
    Silver_City_NM("SVC", "USA", "Silver City, NM"), 
    Singapore("SIN", "Singapore", "Singapore"), 
    Sioux_City_IA("SUX", "USA", "Sioux City, IA"), 
    Sioux_Falls_SD("FSD", "USA", "Sioux Falls, SD"), 
    Sioux_Lookout_ON("YXL", "Canada", "Sioux Lookout, ON"),
    Sitka_AK("SIT", "USA", "Sitka, AK"), 
    Skagway_AK("SGY", "USA", "Skagway, AK"), 
    Skelleftea("SFT", "Sweden", "Skelleftea"), 
    Skopje("SKP", "Macedonia", "Skopje"), 
    Smithers_BC("YYD", "Canada", "Smithers, BC"),
    Sofia("SOF", "Bulgaria", "Sofia"), 
    Sonderborg("SGD", "Denmark", "Sonderborg"), 
    Songpan_Jiuzhai_Huanglong("JZH", "China", "Songpan Jiuzhai Huanglong"), 
    South_Andros("TZN", "Bahamas", "South Andros"), 
    South_Bend_IN("SBN", "USA", "South Bend, IN"), 
    Southampton("SOU", "England", "Southampton"), 
    Split("SPU", "Croatia", "Split"), 
    Spokane_WA("GEG", "USA", "Spokane, WA"), 
    Springfield_IL("SPI", "USA", "Springfield, IL"), 
    Springfield_MA("CEF", "USA", "Springfield, MA"), 
    Springfield_MO("SGF", "USA", "Springfield, MO"), 
    Springfield_VT("VSF", "USA", "Springfield, VT"), 
    St_Cloud_MN("STC", "USA", "St. Cloud, MN"), 
    St_George_UT("SGU", "USA", "St. George, UT"), 
    St_Georges("GND", "Grenada", "St. George's"), 
    St_Johns("ANU", "Antigua", "St. John's"), 
    St_Johns_NL("YYT", "Canada", "St. John's, NL"),
    St_Louis_MO("STL", "USA", "St. Louis, MO"), 
    St_Petersburg("LED", "Russia", "St. Petersburg"), 
    St_Petersburg_FL("PIE", "USA", "St. Petersburg, FL"), 
    State_College_PA("SCE", "USA", "State College, PA"), 
    Stavanger("SVG", "Norway", "Stavanger"), 
    Steamboat_Springs_CO("SBS", "USA", "Steamboat Springs, CO"), 
    Stella_Maris_Long_Island("SML", "Bahamas", "Stella Maris, Long Island"), 
    Stockholm1("ARN", "Sweden", "Stockholm (Arlanda)"), 
    Stockholm2("BMA", "Sweden", "Stockholm (Bromma)"), 
    Stockholm3("STO", "Sweden", "Stockholm"), 
    Stornoway_Isle_of_Lewis("SYY", "Scotland", "Stornoway, Isle of Lewis"), 
    Storuman("SQO", "Sweden", "Storuman"), 
    Strasbourg("SXB", "France", "Strasbourg"), 
    Stuttgart("STR", "Germany", "Stuttgart"), 
    Subic_Bay("SFS", "Philippines", "Subic Bay"), 
    Sudbury_ON("YSB", "Canada", "Sudbury, ON"),
    Sukhothai("THS", "Thailand", "Sukhothai"), 
    Sun_Valley_ID("SUN", "USA", "Sun Valley, ID"), 
    Sundsvall("SDL", "Sweden", "Sundsvall"), 
    Surabaya_Java("SUB", "Indonesia", "Surabaya, Java"), 
    Surat_Thani("URT", "Thailand", "Surat Thani"), 
    Suva("SUV", "Fiji", "Suva"), 
    Sydney_Cape_Breton_Island_NS("YQY", "Canada", "Sydney, Cape Breton Island, NS"),
    Sydney_NSW("SYD", "Australia", "Sydney, NSW"), 
    Syracuse_NY("SYR", "USA", "Syracuse, NY"), 
    Szczecin("SZZ", "Poland", "Szczecin"), 
    Taba("TCP", "Egypt", "Taba"), 
    Tabriz("TBZ", "Iran", "Tabriz"), 
    Tacloban("TAC", "Philippines", "Tacloban"), 
    Taegu("TAE", "South Korea", "Taegu"), 
    Tagbilaran("TAG", "Philippines", "Tagbilaran"), 
    Taichung("RMQ", "Taiwan", "Taichung"), 
    Taipei1("TPE", "Taiwan", "Taipei"), 
    Taipei2("TSA", "Taiwan", "Taipei (Songshan)"), 
    Taiyuan("TYN", "China", "Taiyuan"), 
    Takamatsu("TAK", "Japan", "Takamatsu"), 
    Tallahassee_FL("TLH", "USA", "Tallahassee, FL"), 
    Tallinn("TLL", "Estonia", "Tallinn"), 
    Tampa_FL("TPA", "USA", "Tampa, FL"), 
    Tampere("TMP", "Finland", "Tampere"), 
    Tampico("TAM", "Mexico", "Tampico"), 
    Tamworth_NSW("TMW", "Australia", "Tamworth, NSW"), 
    Tangier("TNG", "Morocco", "Tangier"), 
    Tapachula("TAP", "Mexico", "Tapachula"), 
    Tashkent("TAS", "Uzbekistan", "Tashkent"), 
    Taupo("TUO", "New Zealand", "Taupo"), 
    Tauranga("TRG", "New Zealand", "Tauranga"), 
    Tawau_Sabah("TWU", "Malaysia", "Tawau, Sabah"), 
    Tbilisi("TBS", "Georgia", "Tbilisi"), 
    Teesside("MME", "England", "Teesside"), 
    Tegucigalpa("TGU", "Honduras", "Tegucigalpa"), 
    Tehran("THR", "Iran", "Tehran"), 
    Tel_Aviv("TLV", "Israel", "Tel Aviv"), 
    Telluride_CO("TEX", "USA", "Telluride, CO"), 
    Temuco("ZCO", "Chile", "Temuco"),
    Tenerife_Island("TFS", "Canary Islands (Spain)", "Tenerife Island"), 
    Thomasville_GA("TVI", "USA", "Thomasville, GA"), 
    Tepic("TPQ", "Mexico", "Tepic"), 
    Termez("TMJ", "Uzbekistan", "Termez"), 
    Terrace_BC("YXT", "Canada", "Terrace, BC"),
    Texarkana_AR("TXK", "USA", "Texarkana, AR"), 
    The_Valley("AXA", "Anguilla", "The Valley"), 
    Thessaloniki("SKG", "Greece", "Thessaloniki"), 
    Thief_River_Falls_MN("TVF", "USA", "Thief River Falls, MN"), 
    Thira_Santorini_Island("JTR", "Greece", "Thira, Santorini Island"), 
    Thompson_MB("YTH", "Canada", "Thompson, MB"),
    Thunder_Bay_ON("YQT", "Canada", "Thunder Bay, ON"),
    Tianjin("TSN", "China", "Tianjin"), 
    Tijuana("TIJ", "Mexico", "Tijuana"), 
    Timaru("TIU", "New Zealand", "Timaru"), 
    Timmins_ON("YTS", "Canada", "Timmins, ON"),
    Tirana("TIA", "Albania", "Tirana"), 
    Tobago("TAB", "Trinidad and Tobago", "Tobago"), 
    Toksook_Bay_AK("OOK", "USA", "Toksook Bay, AK"), 
    Tokyo1("HND", "Japan", "Tokyo (Haneda)"), 
    Tokyo2("NRT", "Japan", "Tokyo (Narita)"), 
    Tokyo3("TYO", "Japan", "Tokyo"), 
    Toledo_OH("TOL", "USA", "Toledo, OH"), 
    Toluca("TLC", "Mexico", "Toluca"), 
    Tongren("TEN", "China", "Tongren"), 
    Topeka_KS("TOP", "USA", "Topeka, KS"), 
    Toronto_ON1("YTO", "Canada", "Toronto, ON"), 
    Toronto_ON2("YTZ", "Canada", "Toronto, ON (Billy Bishop)"), 
    Toronto_ON3("YYZ", "Canada", "Toronto, ON (Pearson)"),
    Torreon("TRC", "Mexico", "Torreon"), 
    Toulon("TLN", "France", "Toulon"), 
    Toulouse("TLS", "France", "Toulouse"), 
    Townsville_QLD("TSV", "Australia", "Townsville, Qld"), 
    Trang("TST", "Thailand", "Trang"), 
    Trat("TDX", "Thailand", "Trat"), 
    Traverse_City_MI("TVC", "USA", "Traverse City, MI"), 
    Treasure_Cay_Abaco_Island("TCB", "Bahamas", "Treasure Cay, Abaco Island"), 
    Trenton_NJ("TTN", "USA", "Trenton, NJ"), 
    Tri_City_Airport_TN("TRI", "USA", "Tri-City Airport, TN"), 
    Trieste("TRS", "Italy", "Trieste"), 
    Tripoli("TIP", "Libya", "Tripoli"), 
    Tromso("TOS", "Norway", "Tromso"), 
    Trondheim("TRD", "Norway", "Trondheim"), 
    Truk("TKK", "Micronesia", "Truk"), 
    Tucson_AZ("TUS", "USA", "Tucson, AZ"), 
    Tulsa_OK("TUL", "USA", "Tulsa, OK"), 
    Tunis("TUN", "Tunisia", "Tunis"), 
    Tupelo_MS("TUP", "USA", "Tupelo, MS"), 
    Turin("TRN", "Italy", "Turin"), 
    Turku("TKU", "Finland", "Turku"), 
    Tuxtla_Gutierrez("TGZ", "Mexico", "Tuxtla Gutierrez"), 
    Twin_Falls_ID("TWF", "USA", "Twin Falls, ID"), 
    Tyler_TX("TYR", "USA", "Tyler, TX"), 
    Ubon_Ratchathani("UBP", "Thailand", "Ubon Ratchathani"), 
    Udon_Thani("UTH", "Thailand", "Udon Thani"), 
    Ujung_Pandang_Sulawesi("UPG", "Indonesia", "Ujung Pandang, Sulawesi"), 
    Ulan_Bator("ULN", "Mongolia", "Ulan Bator"), 
    Umea("UME", "Sweden", "Umea"), 
    Una("UNA", "Brazil", "Una"), 
    Unalakleet_AK("UNK", "USA", "Unalakleet, AK"), 
    Urumqi_Sinkiang("URC", "China", "Urumqi, Sinkiang"), 
    Ushuaia_Tierra_del_Fuego("USH", "Argentina", "Ushuaia, Tierra del Fuego"), 
    Ust_Kamenogorsk("UKK", "Kazakhstan", "Ust Kamenogorsk"), 
    Utapao("UTP", "Thailand", "Utapao"), 
    Vaasa("VAA", "Finland", "Vaasa"), 
    Vail_CO("EGE", "USA", "Vail, CO"), 
    Val_dOr_QC("YVO", "Canada", "Val-d'Or, QC"),
    Valdez_AK("VDZ", "USA", "Valdez, AK"), 
    Valdivia("ZAL", "Chile", "Valdivia"), 
    Valdosta_GA("VLD", "USA", "Valdosta, GA"), 
    Valencia("VLC", "Spain", "Valencia"), 
    Valladolid("VLL", "Spain", "Valladolid"), 
    Valletta("MLA", "Malta", "Valletta"), 
    Vancouver_BC("YVR", "Canada", "Vancouver, BC"),
    Varanasi("VNS", "India", "Varanasi"), 
    Varna("VAR", "Bulgaria", "Varna"), 
    Vasteras("VST", "Sweden", "Vasteras"), 
    Vaxjo("VXO", "Sweden", "Vaxjo"), 
    Venice("VCE", "Italy", "Venice"), 
    Veracruz("VER", "Mexico", "Veracruz"), 
    Verona("VRN", "Italy", "Verona"), 
    Victoria_BC("YYJ", "Canada", "Victoria, BC"),
    Victoria_Mahe_Island("SEZ", "Seychelles", "Victoria, Mahe Island"), 
    Victoria_TX("VCT", "USA", "Victoria, TX"), 
    Vienna("VIE", "Austria", "Vienna"), 
    Vientiane("VTE", "Laos", "Vientiane"), 
    Vieques("VQS", "Puerto Rico", "Vieques"), 
    Vieux_Fort("UVF", "St. Lucia", "Vieux Fort"), 
    Vigo("VGO", "Spain", "Vigo"), 
    Vilhelmina("VHM", "Sweden", "Vilhelmina"), 
    Villahermosa("VSA", "Mexico", "Villahermosa"), 
    Vilnius("VNO", "Lithuania", "Vilnius"), 
    Vinh_City("VII", "Vietnam", "Vinh City"), 
    Visalia_CA("VIS", "USA", "Visalia, CA"), 
    Visby("VBY", "Sweden", "Visby"), 
    Vitoria("VIT", "Spain", "Vitoria"), 
    Vladivostok_Siberia("VVO", "Russia", "Vladivostok, Siberia"), 
    Volgograd("VOG", "Russia", "Volgograd"), 
    Wabush_Labrador_NL("YWK", "Canada", "Wabush, Labrador, NL"),
    Waco_TX("ACT", "USA", "Waco, TX"), 
    Wagga_Wagga_NSW("WGA", "Australia", "Wagga-Wagga, NSW"), 
    Wajima("NTQ", "Japan", "Wajima"), 
    Walla_Walla_WA("ALW", "USA", "Walla Walla, WA"), 
    Wanganui("WAG", "New Zealand", "Wanganui"), 
    Warri("QRW", "Nigeria", "Warri"), 
    Warsaw("WAW", "Poland", "Warsaw"), 
    Washington_DC1("DCA", "USA", "Washington DC (Ronald Reagan)"), 
    Washington_DC2("IAD", "USA", "Washington DC (Dulles)"), 
    Washington_DC3("WAS", "USA", "Washington DC"), 
    Waterloo_IA("ALO", "USA", "Waterloo, IA"), 
    Watertown_NY("ART", "USA", "Watertown, NY"), 
    Watertown_SD("ATY", "USA", "Watertown, SD"), 
    Wausau_WI("CWA", "USA", "Wausau, WI"), 
    Weipa_QLD("WEI", "Australia", "Weipa, Qld"), 
    Wellington("WLG", "New Zealand", "Wellington"), 
    Wenatchee_WA("EAT", "USA", "Wenatchee, WA"), 
    West_Palm_Beach_FL("PBI", "USA", "West Palm Beach, FL"), 
    West_Yellowstone_MT("WYS", "USA", "West Yellowstone, MT"), 
    Westport("WSZ", "New Zealand", "Westport"), 
    Whakatane("WHK", "New Zealand", "Whakatane"), 
    Whangarei("WRE", "New Zealand", "Whangarei"), 
    White_Plains_NY("HPN", "USA", "White Plains, NY"), 
    Whitehorse_YT("YXY", "Canada", "Whitehorse, YT"),
    Whyalla_SA("WYA", "Australia", "Whyalla, SA"), 
    Wichita_Falls_TX("SPS", "USA", "Wichita Falls, TX"), 
    Wichita_KS("ICT", "USA", "Wichita, KS"), 
    Wick("WIC", "Scotland", "Wick"), 
    Wilkes_Barre_PA("AVP", "USA", "Wilkes-Barre, PA"), 
    Willemstad("CUR", "Curacao", "Willemstad"), 
    Williams_Lake_BC("YWL", "Canada", "Williams Lake, BC"),
    Williamsport_PA("IPT", "USA", "Williamsport, PA"), 
    Williston_ND("ISN", "USA", "Williston, ND"), 
    Wilmington_DE("ILG", "USA", "Wilmington, DE"), 
    Wilmington_NC("ILM", "USA", "Wilmington, NC"), 
    Windsor_ON("YQG", "Canada", "Windsor, ON"),
    Winnipeg_MB("YWG", "Canada", "Winnipeg, MB"),
    Wolf_Point_MT("OLF", "USA", "Wolf Point, MT"), 
    Worland_WY("WRL", "USA", "Worland, WY"), 
    Wrangell_AK("WRG", "USA", "Wrangell, AK"), 
    Wroclaw("WRO", "Poland", "Wroclaw"), 
    Wuhan("WUH", "China", "Wuhan"), 
    Xian("XIY", "China", "Xi'an"), 
    Xiamen("XMN", "China", "Xiamen"), 
    Xichang("XIC", "China", "Xichang"), 
    Yakima_WA("YKM", "USA", "Yakima, WA"), 
    Yakutat_AK("YAK", "USA", "Yakutat, AK"), 
    Yamagata("GAJ", "Japan", "Yamagata"), 
    Yangyang_Korea("YNY", "Republic of", "Yangyang, Korea"), 
    Yanji("YNJ", "China", "Yanji"), 
    Yantai("YNT", "China", "Yantai"), 
    Yaounde1("NSI", "Cameroon", "Yaounde (Nsimalen)"), 
    Yaounde2("YAO", "Cameroon", "Yaounde"), 
    Yap("YAP", "Micronesia", "Yap"), 
    Yellowknife_NT("YZF", "Canada", "Yellowknife, NT"),
    Yerevan("EVN", "Armenia", "Yerevan"), 
    Yogyakarta_Java("JOG", "Indonesia", "Yogyakarta, Java"), 
    Yuma_AZ("YUM", "USA", "Yuma, AZ"), 
    Zacatecas("ZCL", "Mexico", "Zacatecas"), 
    Zadar("ZAD", "Croatia", "Zadar"), 
    Zagreb("ZAG", "Croatia", "Zagreb"), 
    Zamboanga("ZAM", "Philippines", "Zamboanga"), 
    Zanzibar("ZNZ", "Tanzania", "Zanzibar"), 
    Zaragoza("ZAZ", "Spain", "Zaragoza"), 
    Zhengzhou("CGO", "China", "Zhengzhou"), 
    Zhoushan("HSN", "China", "Zhoushan"), 
    Zurich("ZRH", "Switzerland", "Zurich");

    private String code;
    private String country;
    private String location;

    AirportCode(String code, String country, String location)
    {
        this.code = code;
        this.country = country;
        this.location = location;
    }

    public String getCode() 
    {
        return code;
    }

    public String getCountry()
    {
        return country;
    }

    public String getLocation()
    {
        return location;
    }
}